/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlternateStatementDescriptors } from './alternateStatementDescriptors';
import { ApplicationFee } from './applicationFee';
import { ApplicationFeeOriginatingTransaction } from './applicationFeeOriginatingTransaction';
import { BalanceTransaction } from './balanceTransaction';
import { BillingDetails } from './billingDetails';
import { Charge } from './charge';
import { ChargeApplication } from './chargeApplication';
import { ChargeApplicationFee } from './chargeApplicationFee';
import { ChargeCustomer } from './chargeCustomer';
import { ChargeFraudDetails1 } from './chargeFraudDetails1';
import { ChargeInvoice } from './chargeInvoice';
import { ChargeOnBehalfOf } from './chargeOnBehalfOf';
import { ChargeOutcome1 } from './chargeOutcome1';
import { ChargePaymentMethodDetails } from './chargePaymentMethodDetails';
import { ChargeReview } from './chargeReview';
import { ChargeShipping } from './chargeShipping';
import { ChargeSourceTransfer } from './chargeSourceTransfer';
import { ChargeTransferData1 } from './chargeTransferData1';
import { ConnectCollectionTransfer } from './connectCollectionTransfer';
import { Dispute } from './dispute';
import { DisputeEvidenceDetails } from './disputeEvidenceDetails';
import { FeeRefund } from './feeRefund';
import { FeeRefundBalanceTransaction } from './feeRefundBalanceTransaction';
import { FeeRefundFee } from './feeRefundFee';
import { IssuingAuthorization } from './issuingAuthorization';
import { IssuingAuthorizationMerchantData } from './issuingAuthorizationMerchantData';
import { IssuingAuthorizationNetworkData1 } from './issuingAuthorizationNetworkData1';
import { IssuingAuthorizationPendingRequest1 } from './issuingAuthorizationPendingRequest1';
import { IssuingAuthorizationRequest } from './issuingAuthorizationRequest';
import { IssuingAuthorizationVerificationData } from './issuingAuthorizationVerificationData';
import { IssuingDispute } from './issuingDispute';
import { IssuingDisputeEvidence } from './issuingDisputeEvidence';
import { IssuingDisputeTransaction } from './issuingDisputeTransaction';
import { IssuingTransaction } from './issuingTransaction';
import { IssuingTransactionAmountDetails1 } from './issuingTransactionAmountDetails1';
import { IssuingTransactionAuthorization } from './issuingTransactionAuthorization';
import { IssuingTransactionCard } from './issuingTransactionCard';
import { IssuingTransactionCardholder } from './issuingTransactionCardholder';
import { IssuingTransactionDispute } from './issuingTransactionDispute';
import { IssuingTransactionPurchaseDetails1 } from './issuingTransactionPurchaseDetails1';
import { IssuingTransactionTreasury1 } from './issuingTransactionTreasury1';
import { Level3 } from './level3';
import { Payout } from './payout';
import { PayoutOriginalPayout } from './payoutOriginalPayout';
import { PayoutReversedBy } from './payoutReversedBy';
import { PlatformTaxFee } from './platformTaxFee';
import { RadarRadarOptions } from './radarRadarOptions';
import { Refund } from './refund';
import { RefundCharge } from './refundCharge';
import { RefundFailureBalanceTransaction } from './refundFailureBalanceTransaction';
import { RefundList1 } from './refundList1';
import { RefundNextAction } from './refundNextAction';
import { RefundPaymentIntent } from './refundPaymentIntent';
import { RefundSourceTransferReversal } from './refundSourceTransferReversal';
import { RefundTransferReversal } from './refundTransferReversal';
import { ReserveTransaction } from './reserveTransaction';
import { TaxDeductedAtSource } from './taxDeductedAtSource';
import { Topup } from './topup';
import { TopupSource } from './topupSource';
import { Transfer } from './transfer';
import { TransferDestination } from './transferDestination';
import { TransferDestinationPayment } from './transferDestinationPayment';
import { TransferReversal } from './transferReversal';
import { TransferReversalDestinationPaymentRefund } from './transferReversalDestinationPaymentRefund';
import { TransferReversalList1 } from './transferReversalList1';
import { TransferReversalSourceRefund } from './transferReversalSourceRefund';
import { TransferReversalTransfer } from './transferReversalTransfer';
import { TransferSourceTransaction } from './transferSourceTransaction';

export class BalanceTransactionSource {
    /**
    * The Connected account that incurred this charge.
    */
    'account': string;
    /**
    * Amount, in %s.
    */
    'amount': number;
    /**
    * Amount in %s refunded (can be less than the amount attribute on the charge if a partial refund was issued).
    */
    'amountRefunded': number;
    'application': ChargeApplication | null;
    'balanceTransaction': FeeRefundBalanceTransaction | null;
    'charge': RefundCharge | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': BalanceTransactionSource.ObjectEnum;
    'originatingTransaction': ApplicationFeeOriginatingTransaction | null;
    /**
    * Whether the charge has been fully refunded. If the charge is only partially refunded, this attribute will still be false.
    */
    'refunded': boolean;
    'refunds': RefundList1 | null;
    'alternateStatementDescriptors'?: AlternateStatementDescriptors;
    /**
    * Amount in %s captured (can be less than the amount attribute on the charge if a partial capture was made).
    */
    'amountCaptured': number;
    'applicationFee': ChargeApplicationFee | null;
    /**
    * The amount of the application fee (if any) requested for the charge. [See the Connect documentation](https://stripe.com/docs/connect/direct-charges#collecting-fees) for details.
    */
    'applicationFeeAmount': number | null;
    /**
    * Authorization code on the charge.
    */
    'authorizationCode'?: string;
    'billingDetails': BillingDetails;
    /**
    * The full statement descriptor that is passed to card networks, and that is displayed on your customers\' credit card and bank statements. Allows you to see what the statement descriptor looks like after the static and dynamic portions are combined.
    */
    'calculatedStatementDescriptor': string | null;
    /**
    * If the charge was created without capturing, this Boolean represents whether it is still uncaptured or has since been captured.
    */
    'captured': boolean;
    'customer': ChargeCustomer | null;
    /**
    * An arbitrary string attached to the object. Often useful for displaying to users.
    */
    'description': string | null;
    'destination': TransferDestination | null;
    'dispute': IssuingTransactionDispute | null;
    /**
    * Whether the charge has been disputed.
    */
    'disputed': boolean;
    'failureBalanceTransaction': RefundFailureBalanceTransaction;
    /**
    * Error code explaining reason for top-up failure if available (see [the errors section](https://stripe.com/docs/api#errors) for a list of codes).
    */
    'failureCode': string | null;
    /**
    * Message to user further explaining reason for top-up failure if available.
    */
    'failureMessage': string | null;
    'fraudDetails': ChargeFraudDetails1 | null;
    'invoice': ChargeInvoice | null;
    'level3'?: Level3;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; } | null;
    'onBehalfOf': ChargeOnBehalfOf | null;
    'outcome': ChargeOutcome1 | null;
    /**
    * `true` if the charge succeeded, or was successfully authorized for later capture.
    */
    'paid': boolean;
    'paymentIntent': RefundPaymentIntent | null;
    /**
    * ID of the payment method used in this charge.
    */
    'paymentMethod': string | null;
    'paymentMethodDetails': ChargePaymentMethodDetails | null;
    'radarOptions'?: RadarRadarOptions;
    /**
    * This is the email address that the receipt for this charge was sent to.
    */
    'receiptEmail': string | null;
    /**
    * This is the transaction number that appears on email receipts sent for this refund.
    */
    'receiptNumber': string | null;
    /**
    * This is the URL to view the receipt for this charge. The receipt is kept up-to-date to the latest state of the charge, including any refunds. If the charge is for an Invoice, the receipt will be stylized as an Invoice receipt.
    */
    'receiptUrl': string | null;
    'review': ChargeReview | null;
    'shipping': ChargeShipping | null;
    'source': TopupSource | null;
    'sourceTransfer': ChargeSourceTransfer | null;
    /**
    * Extra information about a top-up. This will appear on your source\'s bank statement. It must contain at least one letter.
    */
    'statementDescriptor': string | null;
    /**
    * Provides information about the charge that customers see on their statements. Concatenated with the prefix (shortened descriptor) or statement descriptor that’s set on the account to form the complete statement descriptor. Maximum 22 characters for the concatenated descriptor.
    */
    'statementDescriptorSuffix': string | null;
    /**
    * The status of the top-up is either `canceled`, `failed`, `pending`, `reversed`, or `succeeded`.
    */
    'status': BalanceTransactionSource.StatusEnum;
    'transfer': TransferReversalTransfer;
    'transferData': ChargeTransferData1 | null;
    /**
    * A string that identifies this transaction as part of a group. See the [Connect documentation](https://stripe.com/docs/connect/charges-transfers#transfer-options) for details.
    */
    'transferGroup': string | null;
    /**
    * List of balance transactions associated with the dispute.
    */
    'balanceTransactions': Array<BalanceTransaction> | null;
    'evidence': IssuingDisputeEvidence;
    'evidenceDetails': DisputeEvidenceDetails;
    /**
    * If true, it is still possible to refund the disputed payment. Once the payment has been fully refunded, no further funds will be withdrawn from your Stripe account as a result of this dispute.
    */
    'isChargeRefundable': boolean;
    /**
    * Network-dependent reason code for the dispute.
    */
    'networkReasonCode'?: string | null;
    /**
    * Reason for the refund, either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
    */
    'reason': BalanceTransactionSource.ReasonEnum;
    'fee': FeeRefundFee;
    'amountDetails': IssuingTransactionAmountDetails1 | null;
    /**
    * Whether the authorization has been approved.
    */
    'approved': boolean;
    /**
    * How the card details were provided.
    */
    'authorizationMethod': BalanceTransactionSource.AuthorizationMethodEnum;
    'card': IssuingTransactionCard;
    'cardholder': IssuingTransactionCardholder | null;
    /**
    * The amount that the merchant will receive, denominated in `merchant_currency` and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal). It will be different from `amount` if the merchant is taking payment in a different currency.
    */
    'merchantAmount': number;
    /**
    * The currency with which the merchant is taking payment.
    */
    'merchantCurrency': string;
    'merchantData': IssuingAuthorizationMerchantData;
    'networkData': IssuingAuthorizationNetworkData1 | null;
    'pendingRequest': IssuingAuthorizationPendingRequest1 | null;
    /**
    * History of every time a `pending_request` authorization was approved/declined, either by you directly or by Stripe (e.g. based on your spending_controls). If the merchant changes the authorization by performing an incremental authorization, you can look at this field to see the previous requests for the authorization. This field can be helpful in determining why a given authorization was approved/declined.
    */
    'requestHistory': Array<IssuingAuthorizationRequest>;
    /**
    * List of [transactions](https://stripe.com/docs/api/issuing/transactions) associated with this authorization.
    */
    'transactions': Array<IssuingTransaction>;
    'treasury'?: IssuingTransactionTreasury1 | null;
    'verificationData': IssuingAuthorizationVerificationData;
    /**
    * The digital wallet used for this transaction. One of `apple_pay`, `google_pay`, or `samsung_pay`.
    */
    'wallet': BalanceTransactionSource.WalletEnum;
    'transaction': IssuingDisputeTransaction;
    'authorization': IssuingTransactionAuthorization | null;
    'purchaseDetails': IssuingTransactionPurchaseDetails1 | null;
    /**
    * The type of tax (VAT).
    */
    'type': string;
    /**
    * Date the payout is expected to arrive in the bank. This factors in delays like weekends or bank holidays.
    */
    'arrivalDate': number;
    /**
    * Returns `true` if the payout was created by an [automated payout schedule](https://stripe.com/docs/payouts#payout-schedule), and `false` if it was [requested manually](https://stripe.com/docs/payouts#manual-payouts).
    */
    'automatic': boolean;
    /**
    * The method used to send this payout, which can be `standard` or `instant`. `instant` is only supported for payouts to debit cards. (See [Instant payouts for marketplaces](https://stripe.com/blog/instant-payouts-for-marketplaces) for more information.)
    */
    'method': string;
    'originalPayout': PayoutOriginalPayout | null;
    'reversedBy': PayoutReversedBy | null;
    /**
    * The source balance this transfer came from. One of `card`, `fpx`, or `bank_account`.
    */
    'sourceType': string;
    'sourceTransaction': TransferSourceTransaction | null;
    /**
    * If the refund failed, the reason for refund failure if known. Possible values are `lost_or_stolen_card`, `expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, `declined`, `merchant_request` or `unknown`.
    */
    'failureReason'?: string;
    /**
    * Email to which refund instructions, if required, are sent to.
    */
    'instructionsEmail'?: string;
    'nextAction'?: RefundNextAction;
    'sourceTransferReversal': RefundSourceTransferReversal | null;
    'transferReversal': RefundTransferReversal | null;
    /**
    * The end of the invoicing period. This TDS applies to Stripe fees collected during this invoicing period.
    */
    'periodEnd': number;
    /**
    * The start of the invoicing period. This TDS applies to Stripe fees collected during this invoicing period.
    */
    'periodStart': number;
    /**
    * The TAN that was supplied to Stripe when TDS was assessed
    */
    'taxDeductionAccountNumber': string;
    /**
    * Date the funds are expected to arrive in your Stripe account for payouts. This factors in delays like weekends or bank holidays. May not be specified depending on status of top-up.
    */
    'expectedAvailabilityDate': number | null;
    /**
    * Amount in %s reversed (can be less than the amount attribute on the transfer if a partial reversal was issued).
    */
    'amountReversed': number;
    'destinationPayment'?: TransferDestinationPayment;
    'reversals': TransferReversalList1;
    /**
    * Whether the transfer has been fully reversed. If the transfer is only partially reversed, this attribute will still be false.
    */
    'reversed': boolean;
    'destinationPaymentRefund': TransferReversalDestinationPaymentRefund | null;
    'sourceRefund': TransferReversalSourceRefund | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountRefunded",
            "baseName": "amount_refunded",
            "type": "number"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "ChargeApplication"
        },
        {
            "name": "balanceTransaction",
            "baseName": "balance_transaction",
            "type": "FeeRefundBalanceTransaction"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "RefundCharge"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "BalanceTransactionSource.ObjectEnum"
        },
        {
            "name": "originatingTransaction",
            "baseName": "originating_transaction",
            "type": "ApplicationFeeOriginatingTransaction"
        },
        {
            "name": "refunded",
            "baseName": "refunded",
            "type": "boolean"
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "RefundList1"
        },
        {
            "name": "alternateStatementDescriptors",
            "baseName": "alternate_statement_descriptors",
            "type": "AlternateStatementDescriptors"
        },
        {
            "name": "amountCaptured",
            "baseName": "amount_captured",
            "type": "number"
        },
        {
            "name": "applicationFee",
            "baseName": "application_fee",
            "type": "ChargeApplicationFee"
        },
        {
            "name": "applicationFeeAmount",
            "baseName": "application_fee_amount",
            "type": "number"
        },
        {
            "name": "authorizationCode",
            "baseName": "authorization_code",
            "type": "string"
        },
        {
            "name": "billingDetails",
            "baseName": "billing_details",
            "type": "BillingDetails"
        },
        {
            "name": "calculatedStatementDescriptor",
            "baseName": "calculated_statement_descriptor",
            "type": "string"
        },
        {
            "name": "captured",
            "baseName": "captured",
            "type": "boolean"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "ChargeCustomer"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "TransferDestination"
        },
        {
            "name": "dispute",
            "baseName": "dispute",
            "type": "IssuingTransactionDispute"
        },
        {
            "name": "disputed",
            "baseName": "disputed",
            "type": "boolean"
        },
        {
            "name": "failureBalanceTransaction",
            "baseName": "failure_balance_transaction",
            "type": "RefundFailureBalanceTransaction"
        },
        {
            "name": "failureCode",
            "baseName": "failure_code",
            "type": "string"
        },
        {
            "name": "failureMessage",
            "baseName": "failure_message",
            "type": "string"
        },
        {
            "name": "fraudDetails",
            "baseName": "fraud_details",
            "type": "ChargeFraudDetails1"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "ChargeInvoice"
        },
        {
            "name": "level3",
            "baseName": "level3",
            "type": "Level3"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "onBehalfOf",
            "baseName": "on_behalf_of",
            "type": "ChargeOnBehalfOf"
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "ChargeOutcome1"
        },
        {
            "name": "paid",
            "baseName": "paid",
            "type": "boolean"
        },
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "RefundPaymentIntent"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "string"
        },
        {
            "name": "paymentMethodDetails",
            "baseName": "payment_method_details",
            "type": "ChargePaymentMethodDetails"
        },
        {
            "name": "radarOptions",
            "baseName": "radar_options",
            "type": "RadarRadarOptions"
        },
        {
            "name": "receiptEmail",
            "baseName": "receipt_email",
            "type": "string"
        },
        {
            "name": "receiptNumber",
            "baseName": "receipt_number",
            "type": "string"
        },
        {
            "name": "receiptUrl",
            "baseName": "receipt_url",
            "type": "string"
        },
        {
            "name": "review",
            "baseName": "review",
            "type": "ChargeReview"
        },
        {
            "name": "shipping",
            "baseName": "shipping",
            "type": "ChargeShipping"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "TopupSource"
        },
        {
            "name": "sourceTransfer",
            "baseName": "source_transfer",
            "type": "ChargeSourceTransfer"
        },
        {
            "name": "statementDescriptor",
            "baseName": "statement_descriptor",
            "type": "string"
        },
        {
            "name": "statementDescriptorSuffix",
            "baseName": "statement_descriptor_suffix",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BalanceTransactionSource.StatusEnum"
        },
        {
            "name": "transfer",
            "baseName": "transfer",
            "type": "TransferReversalTransfer"
        },
        {
            "name": "transferData",
            "baseName": "transfer_data",
            "type": "ChargeTransferData1"
        },
        {
            "name": "transferGroup",
            "baseName": "transfer_group",
            "type": "string"
        },
        {
            "name": "balanceTransactions",
            "baseName": "balance_transactions",
            "type": "Array<BalanceTransaction>"
        },
        {
            "name": "evidence",
            "baseName": "evidence",
            "type": "IssuingDisputeEvidence"
        },
        {
            "name": "evidenceDetails",
            "baseName": "evidence_details",
            "type": "DisputeEvidenceDetails"
        },
        {
            "name": "isChargeRefundable",
            "baseName": "is_charge_refundable",
            "type": "boolean"
        },
        {
            "name": "networkReasonCode",
            "baseName": "network_reason_code",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "BalanceTransactionSource.ReasonEnum"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "FeeRefundFee"
        },
        {
            "name": "amountDetails",
            "baseName": "amount_details",
            "type": "IssuingTransactionAmountDetails1"
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "boolean"
        },
        {
            "name": "authorizationMethod",
            "baseName": "authorization_method",
            "type": "BalanceTransactionSource.AuthorizationMethodEnum"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "IssuingTransactionCard"
        },
        {
            "name": "cardholder",
            "baseName": "cardholder",
            "type": "IssuingTransactionCardholder"
        },
        {
            "name": "merchantAmount",
            "baseName": "merchant_amount",
            "type": "number"
        },
        {
            "name": "merchantCurrency",
            "baseName": "merchant_currency",
            "type": "string"
        },
        {
            "name": "merchantData",
            "baseName": "merchant_data",
            "type": "IssuingAuthorizationMerchantData"
        },
        {
            "name": "networkData",
            "baseName": "network_data",
            "type": "IssuingAuthorizationNetworkData1"
        },
        {
            "name": "pendingRequest",
            "baseName": "pending_request",
            "type": "IssuingAuthorizationPendingRequest1"
        },
        {
            "name": "requestHistory",
            "baseName": "request_history",
            "type": "Array<IssuingAuthorizationRequest>"
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<IssuingTransaction>"
        },
        {
            "name": "treasury",
            "baseName": "treasury",
            "type": "IssuingTransactionTreasury1"
        },
        {
            "name": "verificationData",
            "baseName": "verification_data",
            "type": "IssuingAuthorizationVerificationData"
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "BalanceTransactionSource.WalletEnum"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "IssuingDisputeTransaction"
        },
        {
            "name": "authorization",
            "baseName": "authorization",
            "type": "IssuingTransactionAuthorization"
        },
        {
            "name": "purchaseDetails",
            "baseName": "purchase_details",
            "type": "IssuingTransactionPurchaseDetails1"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "arrivalDate",
            "baseName": "arrival_date",
            "type": "number"
        },
        {
            "name": "automatic",
            "baseName": "automatic",
            "type": "boolean"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "originalPayout",
            "baseName": "original_payout",
            "type": "PayoutOriginalPayout"
        },
        {
            "name": "reversedBy",
            "baseName": "reversed_by",
            "type": "PayoutReversedBy"
        },
        {
            "name": "sourceType",
            "baseName": "source_type",
            "type": "string"
        },
        {
            "name": "sourceTransaction",
            "baseName": "source_transaction",
            "type": "TransferSourceTransaction"
        },
        {
            "name": "failureReason",
            "baseName": "failure_reason",
            "type": "string"
        },
        {
            "name": "instructionsEmail",
            "baseName": "instructions_email",
            "type": "string"
        },
        {
            "name": "nextAction",
            "baseName": "next_action",
            "type": "RefundNextAction"
        },
        {
            "name": "sourceTransferReversal",
            "baseName": "source_transfer_reversal",
            "type": "RefundSourceTransferReversal"
        },
        {
            "name": "transferReversal",
            "baseName": "transfer_reversal",
            "type": "RefundTransferReversal"
        },
        {
            "name": "periodEnd",
            "baseName": "period_end",
            "type": "number"
        },
        {
            "name": "periodStart",
            "baseName": "period_start",
            "type": "number"
        },
        {
            "name": "taxDeductionAccountNumber",
            "baseName": "tax_deduction_account_number",
            "type": "string"
        },
        {
            "name": "expectedAvailabilityDate",
            "baseName": "expected_availability_date",
            "type": "number"
        },
        {
            "name": "amountReversed",
            "baseName": "amount_reversed",
            "type": "number"
        },
        {
            "name": "destinationPayment",
            "baseName": "destination_payment",
            "type": "TransferDestinationPayment"
        },
        {
            "name": "reversals",
            "baseName": "reversals",
            "type": "TransferReversalList1"
        },
        {
            "name": "reversed",
            "baseName": "reversed",
            "type": "boolean"
        },
        {
            "name": "destinationPaymentRefund",
            "baseName": "destination_payment_refund",
            "type": "TransferReversalDestinationPaymentRefund"
        },
        {
            "name": "sourceRefund",
            "baseName": "source_refund",
            "type": "TransferReversalSourceRefund"
        }    ];

    static getAttributeTypeMap() {
        return BalanceTransactionSource.attributeTypeMap;
    }
}

export namespace BalanceTransactionSource {
    export enum ObjectEnum {
        TransferReversal = <any> 'transfer_reversal'
    }
    export enum StatusEnum {
        Canceled = <any> 'canceled',
        Failed = <any> 'failed',
        Pending = <any> 'pending',
        Reversed = <any> 'reversed',
        Succeeded = <any> 'succeeded'
    }
    export enum ReasonEnum {
        Duplicate = <any> 'duplicate',
        ExpiredUncapturedCharge = <any> 'expired_uncaptured_charge',
        Fraudulent = <any> 'fraudulent',
        RequestedByCustomer = <any> 'requested_by_customer'
    }
    export enum AuthorizationMethodEnum {
        Chip = <any> 'chip',
        Contactless = <any> 'contactless',
        KeyedIn = <any> 'keyed_in',
        Online = <any> 'online',
        Swipe = <any> 'swipe'
    }
    export enum WalletEnum {
        ApplePay = <any> 'apple_pay',
        GooglePay = <any> 'google_pay',
        SamsungPay = <any> 'samsung_pay'
    }
}
