/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class BankConnectionsResourceBalanceRefresh {
    /**
    * The time at which the last refresh attempt was initiated. Measured in seconds since the Unix epoch.
    */
    'lastAttemptedAt': number;
    /**
    * The status of the last refresh attempt.
    */
    'status': BankConnectionsResourceBalanceRefresh.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lastAttemptedAt",
            "baseName": "last_attempted_at",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BankConnectionsResourceBalanceRefresh.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return BankConnectionsResourceBalanceRefresh.attributeTypeMap;
    }
}

export namespace BankConnectionsResourceBalanceRefresh {
    export enum StatusEnum {
        Failed = <any> 'failed',
        Pending = <any> 'pending',
        Succeeded = <any> 'succeeded'
    }
}
