/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PortalFlowsFlow } from './portalFlowsFlow';
import { PortalFlowsFlowAfterCompletion } from './portalFlowsFlowAfterCompletion';
import { PortalFlowsFlowSubscriptionCancel1 } from './portalFlowsFlowSubscriptionCancel1';

/**
* Information about a specific flow for the customer to go through. See the [docs](https://stripe.com/docs/customer-management/portal-deep-links) to learn more about using customer portal deep links and flows.
*/
export class BillingPortalSessionFlow {
    'afterCompletion': PortalFlowsFlowAfterCompletion;
    'subscriptionCancel': PortalFlowsFlowSubscriptionCancel1 | null;
    /**
    * Type of flow that the customer will go through.
    */
    'type': BillingPortalSessionFlow.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "afterCompletion",
            "baseName": "after_completion",
            "type": "PortalFlowsFlowAfterCompletion"
        },
        {
            "name": "subscriptionCancel",
            "baseName": "subscription_cancel",
            "type": "PortalFlowsFlowSubscriptionCancel1"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BillingPortalSessionFlow.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return BillingPortalSessionFlow.attributeTypeMap;
    }
}

export namespace BillingPortalSessionFlow {
    export enum TypeEnum {
        PaymentMethodUpdate = <any> 'payment_method_update',
        SubscriptionCancel = <any> 'subscription_cancel'
    }
}
