/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargeFraudDetails } from './chargeFraudDetails';

/**
* Information on fraud assessments for the charge.
*/
export class ChargeFraudDetails1 {
    /**
    * Assessments from Stripe. If set, the value is `fraudulent`.
    */
    'stripeReport'?: string;
    /**
    * Assessments reported by you. If set, possible values of are `safe` and `fraudulent`.
    */
    'userReport'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stripeReport",
            "baseName": "stripe_report",
            "type": "string"
        },
        {
            "name": "userReport",
            "baseName": "user_report",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChargeFraudDetails1.attributeTypeMap;
    }
}

