/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Transfer } from './transfer';
import { TransferBalanceTransaction } from './transferBalanceTransaction';
import { TransferDestination } from './transferDestination';
import { TransferDestinationPayment } from './transferDestinationPayment';
import { TransferReversalList1 } from './transferReversalList1';
import { TransferSourceTransaction } from './transferSourceTransaction';

/**
* ID of the transfer to the `destination` account (only applicable if the charge was created using the `destination` parameter).
*/
export class ChargeTransfer {
    /**
    * Amount in %s to be transferred.
    */
    'amount': number;
    /**
    * Amount in %s reversed (can be less than the amount attribute on the transfer if a partial reversal was issued).
    */
    'amountReversed': number;
    'balanceTransaction': TransferBalanceTransaction | null;
    /**
    * Time that this record of the transfer was first created.
    */
    'created': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string;
    /**
    * An arbitrary string attached to the object. Often useful for displaying to users.
    */
    'description': string | null;
    'destination': TransferDestination | null;
    'destinationPayment'?: TransferDestinationPayment;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; };
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': ChargeTransfer.ObjectEnum;
    'reversals': TransferReversalList1;
    /**
    * Whether the transfer has been fully reversed. If the transfer is only partially reversed, this attribute will still be false.
    */
    'reversed': boolean;
    'sourceTransaction': TransferSourceTransaction | null;
    /**
    * The source balance this transfer came from. One of `card`, `fpx`, or `bank_account`.
    */
    'sourceType'?: string;
    /**
    * A string that identifies this transaction as part of a group. See the [Connect documentation](https://stripe.com/docs/connect/charges-transfers#transfer-options) for details.
    */
    'transferGroup': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountReversed",
            "baseName": "amount_reversed",
            "type": "number"
        },
        {
            "name": "balanceTransaction",
            "baseName": "balance_transaction",
            "type": "TransferBalanceTransaction"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "TransferDestination"
        },
        {
            "name": "destinationPayment",
            "baseName": "destination_payment",
            "type": "TransferDestinationPayment"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "ChargeTransfer.ObjectEnum"
        },
        {
            "name": "reversals",
            "baseName": "reversals",
            "type": "TransferReversalList1"
        },
        {
            "name": "reversed",
            "baseName": "reversed",
            "type": "boolean"
        },
        {
            "name": "sourceTransaction",
            "baseName": "source_transaction",
            "type": "TransferSourceTransaction"
        },
        {
            "name": "sourceType",
            "baseName": "source_type",
            "type": "string"
        },
        {
            "name": "transferGroup",
            "baseName": "transfer_group",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChargeTransfer.attributeTypeMap;
    }
}

export namespace ChargeTransfer {
    export enum ObjectEnum {
        Transfer = <any> 'transfer'
    }
}
