/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargeTransferDataDestination } from './chargeTransferDataDestination';

/**
* 
*/
export class ChargeTransferData {
    /**
    * The amount transferred to the destination account, if specified. By default, the entire charge amount is transferred to the destination account.
    */
    'amount': number | null;
    'destination': ChargeTransferDataDestination;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "ChargeTransferDataDestination"
        }    ];

    static getAttributeTypeMap() {
        return ChargeTransferData.attributeTypeMap;
    }
}

