/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentPagesCheckoutSessionConsent } from './paymentPagesCheckoutSessionConsent';

/**
* Results of `consent_collection` for this session.
*/
export class CheckoutSessionConsent {
    /**
    * If `opt_in`, the customer consents to receiving promotional communications from the merchant about this Checkout Session.
    */
    'promotions': CheckoutSessionConsent.PromotionsEnum;
    /**
    * If `accepted`, the customer in this Checkout Session has agreed to the merchant\'s terms of service.
    */
    'termsOfService': CheckoutSessionConsent.TermsOfServiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "promotions",
            "baseName": "promotions",
            "type": "CheckoutSessionConsent.PromotionsEnum"
        },
        {
            "name": "termsOfService",
            "baseName": "terms_of_service",
            "type": "CheckoutSessionConsent.TermsOfServiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutSessionConsent.attributeTypeMap;
    }
}

export namespace CheckoutSessionConsent {
    export enum PromotionsEnum {
        In = <any> 'opt_in',
        Out = <any> 'opt_out'
    }
    export enum TermsOfServiceEnum {
        Accepted = <any> 'accepted'
    }
}
