/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectCollectionTransferDestination } from './connectCollectionTransferDestination';

/**
* 
*/
export class ConnectCollectionTransfer {
    /**
    * Amount transferred, in %s.
    */
    'amount': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string;
    'destination': ConnectCollectionTransferDestination;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': ConnectCollectionTransfer.ObjectEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "ConnectCollectionTransferDestination"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "ConnectCollectionTransfer.ObjectEnum"
        }    ];

    static getAttributeTypeMap() {
        return ConnectCollectionTransfer.attributeTypeMap;
    }
}

export namespace ConnectCollectionTransfer {
    export enum ObjectEnum {
        ConnectCollectionTransfer = <any> 'connect_collection_transfer'
    }
}
