/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CountrySpecVerificationFields } from './countrySpecVerificationFields';

/**
* Stripe needs to collect certain pieces of information about each account created. These requirements can differ depending on the account\'s country. The Country Specs API makes these rules available to your integration.  You can also view the information from this API call as [an online guide](/docs/connect/required-verification-information).
*/
export class CountrySpec {
    /**
    * The default currency for this country. This applies to both payment methods and bank accounts.
    */
    'defaultCurrency': string;
    /**
    * Unique identifier for the object. Represented as the ISO country code for this country.
    */
    'id': string;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': CountrySpec.ObjectEnum;
    /**
    * Currencies that can be accepted in the specific country (for transfers).
    */
    'supportedBankAccountCurrencies': { [key: string]: Array<string>; };
    /**
    * Currencies that can be accepted in the specified country (for payments).
    */
    'supportedPaymentCurrencies': Array<string>;
    /**
    * Payment methods available in the specified country. You may need to enable some payment methods (e.g., [ACH](https://stripe.com/docs/ach)) on your account before they appear in this list. The `stripe` payment method refers to [charging through your platform](https://stripe.com/docs/connect/destination-charges).
    */
    'supportedPaymentMethods': Array<string>;
    /**
    * Countries that can accept transfers from the specified country.
    */
    'supportedTransferCountries': Array<string>;
    'verificationFields': CountrySpecVerificationFields;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultCurrency",
            "baseName": "default_currency",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "CountrySpec.ObjectEnum"
        },
        {
            "name": "supportedBankAccountCurrencies",
            "baseName": "supported_bank_account_currencies",
            "type": "{ [key: string]: Array<string>; }"
        },
        {
            "name": "supportedPaymentCurrencies",
            "baseName": "supported_payment_currencies",
            "type": "Array<string>"
        },
        {
            "name": "supportedPaymentMethods",
            "baseName": "supported_payment_methods",
            "type": "Array<string>"
        },
        {
            "name": "supportedTransferCountries",
            "baseName": "supported_transfer_countries",
            "type": "Array<string>"
        },
        {
            "name": "verificationFields",
            "baseName": "verification_fields",
            "type": "CountrySpecVerificationFields"
        }    ];

    static getAttributeTypeMap() {
        return CountrySpec.attributeTypeMap;
    }
}

export namespace CountrySpec {
    export enum ObjectEnum {
        CountrySpec = <any> 'country_spec'
    }
}
