/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class CountrySpecVerificationFieldDetails {
    /**
    * Additional fields which are only required for some users.
    */
    'additional': Array<string>;
    /**
    * Fields which every account must eventually provide.
    */
    'minimum': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additional",
            "baseName": "additional",
            "type": "Array<string>"
        },
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CountrySpecVerificationFieldDetails.attributeTypeMap;
    }
}

