/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreditNoteTaxAmount } from './creditNoteTaxAmount';
import { DiscountsResourceDiscountAmount } from './discountsResourceDiscountAmount';
import { TaxRate } from './taxRate';

/**
* 
*/
export class CreditNoteLineItem {
    /**
    * The integer amount in %s representing the gross amount being credited for this line item, excluding (exclusive) tax and discounts.
    */
    'amount': number;
    /**
    * The integer amount in %s representing the amount being credited for this line item, excluding all tax and discounts.
    */
    'amountExcludingTax': number | null;
    /**
    * Description of the item being credited.
    */
    'description': string | null;
    /**
    * The integer amount in %s representing the discount being credited for this line item.
    */
    'discountAmount': number;
    /**
    * The amount of discount calculated per discount for this line item
    */
    'discountAmounts': Array<DiscountsResourceDiscountAmount>;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * ID of the invoice line item being credited
    */
    'invoiceLineItem'?: string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': CreditNoteLineItem.ObjectEnum;
    /**
    * The number of units of product being credited.
    */
    'quantity': number | null;
    /**
    * The amount of tax calculated per tax rate for this line item
    */
    'taxAmounts': Array<CreditNoteTaxAmount>;
    /**
    * The tax rates which apply to the line item.
    */
    'taxRates': Array<TaxRate>;
    /**
    * The type of the credit note line item, one of `invoice_line_item` or `custom_line_item`. When the type is `invoice_line_item` there is an additional `invoice_line_item` property on the resource the value of which is the id of the credited line item on the invoice.
    */
    'type': CreditNoteLineItem.TypeEnum;
    /**
    * The cost of each unit of product being credited.
    */
    'unitAmount': number | null;
    /**
    * Same as `unit_amount`, but contains a decimal value with at most 12 decimal places.
    */
    'unitAmountDecimal': string | null;
    /**
    * The amount in %s representing the unit amount being credited for this line item, excluding all tax and discounts.
    */
    'unitAmountExcludingTax': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountExcludingTax",
            "baseName": "amount_excluding_tax",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "discountAmount",
            "baseName": "discount_amount",
            "type": "number"
        },
        {
            "name": "discountAmounts",
            "baseName": "discount_amounts",
            "type": "Array<DiscountsResourceDiscountAmount>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "invoiceLineItem",
            "baseName": "invoice_line_item",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "CreditNoteLineItem.ObjectEnum"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "taxAmounts",
            "baseName": "tax_amounts",
            "type": "Array<CreditNoteTaxAmount>"
        },
        {
            "name": "taxRates",
            "baseName": "tax_rates",
            "type": "Array<TaxRate>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CreditNoteLineItem.TypeEnum"
        },
        {
            "name": "unitAmount",
            "baseName": "unit_amount",
            "type": "number"
        },
        {
            "name": "unitAmountDecimal",
            "baseName": "unit_amount_decimal",
            "type": "string"
        },
        {
            "name": "unitAmountExcludingTax",
            "baseName": "unit_amount_excluding_tax",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreditNoteLineItem.attributeTypeMap;
    }
}

export namespace CreditNoteLineItem {
    export enum ObjectEnum {
        CreditNoteLineItem = <any> 'credit_note_line_item'
    }
    export enum TypeEnum {
        CustomLineItem = <any> 'custom_line_item',
        InvoiceLineItem = <any> 'invoice_line_item'
    }
}
