/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferResourceEuBankTransfer {
    /**
    * The BIC of the bank of the sender of the funding.
    */
    'bic': string | null;
    /**
    * The last 4 digits of the IBAN of the sender of the funding.
    */
    'ibanLast4': string | null;
    /**
    * The full name of the sender, as supplied by the sending bank.
    */
    'senderName': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bic",
            "baseName": "bic",
            "type": "string"
        },
        {
            "name": "ibanLast4",
            "baseName": "iban_last4",
            "type": "string"
        },
        {
            "name": "senderName",
            "baseName": "sender_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferResourceEuBankTransfer.attributeTypeMap;
    }
}

