/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class FinancialReportingFinanceReportRunRunParameters {
    /**
    * The set of output columns requested for inclusion in the report run.
    */
    'columns'?: Array<string>;
    /**
    * Connected account ID by which to filter the report run.
    */
    'connectedAccount'?: string;
    /**
    * Currency of objects to be included in the report run.
    */
    'currency'?: string;
    /**
    * Ending timestamp of data to be included in the report run. Can be any UTC timestamp between 1 second after the user specified `interval_start` and 1 second before this report\'s last `data_available_end` value.
    */
    'intervalEnd'?: number;
    /**
    * Starting timestamp of data to be included in the report run. Can be any UTC timestamp between 1 second after this report\'s `data_available_start` and 1 second before the user specified `interval_end` value.
    */
    'intervalStart'?: number;
    /**
    * Payout ID by which to filter the report run.
    */
    'payout'?: string;
    /**
    * Category of balance transactions to be included in the report run.
    */
    'reportingCategory'?: string;
    /**
    * Defaults to `Etc/UTC`. The output timezone for all timestamps in the report. A list of possible time zone values is maintained at the [IANA Time Zone Database](http://www.iana.org/time-zones). Has no effect on `interval_start` or `interval_end`.
    */
    'timezone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "columns",
            "baseName": "columns",
            "type": "Array<string>"
        },
        {
            "name": "connectedAccount",
            "baseName": "connected_account",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "intervalEnd",
            "baseName": "interval_end",
            "type": "number"
        },
        {
            "name": "intervalStart",
            "baseName": "interval_start",
            "type": "number"
        },
        {
            "name": "payout",
            "baseName": "payout",
            "type": "string"
        },
        {
            "name": "reportingCategory",
            "baseName": "reporting_category",
            "type": "string"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FinancialReportingFinanceReportRunRunParameters.attributeTypeMap;
    }
}

