/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GelatoSelfieReportError } from './gelatoSelfieReportError';

/**
* Details on the verification error. Present when status is `unverified`.
*/
export class GelatoSelfieReportError1 {
    /**
    * A short machine-readable string giving the reason for the verification failure.
    */
    'code': GelatoSelfieReportError1.CodeEnum;
    /**
    * A human-readable message giving the reason for the failure. These messages can be shown to your users.
    */
    'reason': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "GelatoSelfieReportError1.CodeEnum"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GelatoSelfieReportError1.attributeTypeMap;
    }
}

export namespace GelatoSelfieReportError1 {
    export enum CodeEnum {
        DocumentMissingPhoto = <any> 'selfie_document_missing_photo',
        FaceMismatch = <any> 'selfie_face_mismatch',
        Manipulated = <any> 'selfie_manipulated',
        UnverifiedOther = <any> 'selfie_unverified_other'
    }
}
