/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GelatoDataDocumentReportExpirationDate } from './gelatoDataDocumentReportExpirationDate';

/**
* Expiration date of the document.
*/
export class GelatoDocumentReportExpirationDate {
    /**
    * Numerical day between 1 and 31.
    */
    'day': number | null;
    /**
    * Numerical month between 1 and 12.
    */
    'month': number | null;
    /**
    * The four-digit year.
    */
    'year': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "day",
            "baseName": "day",
            "type": "number"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GelatoDocumentReportExpirationDate.attributeTypeMap;
    }
}

