/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GelatoDocumentReportError } from './gelatoDocumentReportError';

/**
* Details on the verification error. Present when status is `unverified`.
*/
export class GelatoDocumentReportError1 {
    /**
    * A short machine-readable string giving the reason for the verification failure.
    */
    'code': GelatoDocumentReportError1.CodeEnum;
    /**
    * A human-readable message giving the reason for the failure. These messages can be shown to your users.
    */
    'reason': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "GelatoDocumentReportError1.CodeEnum"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GelatoDocumentReportError1.attributeTypeMap;
    }
}

export namespace GelatoDocumentReportError1 {
    export enum CodeEnum {
        Expired = <any> 'document_expired',
        TypeNotSupported = <any> 'document_type_not_supported',
        UnverifiedOther = <any> 'document_unverified_other'
    }
}
