/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GelatoDocumentReportAddress } from './gelatoDocumentReportAddress';
import { GelatoDocumentReportDob } from './gelatoDocumentReportDob';
import { GelatoDocumentReportError1 } from './gelatoDocumentReportError1';
import { GelatoDocumentReportExpirationDate } from './gelatoDocumentReportExpirationDate';
import { GelatoDocumentReportIssuedDate } from './gelatoDocumentReportIssuedDate';

/**
* Result from a document check
*/
export class GelatoDocumentReport {
    'address': GelatoDocumentReportAddress | null;
    'dob': GelatoDocumentReportDob | null;
    'error': GelatoDocumentReportError1 | null;
    'expirationDate': GelatoDocumentReportExpirationDate | null;
    /**
    * Array of [File](https://stripe.com/docs/api/files) ids containing images for this document.
    */
    'files': Array<string> | null;
    /**
    * First name as it appears in the document.
    */
    'firstName': string | null;
    'issuedDate': GelatoDocumentReportIssuedDate | null;
    /**
    * Issuing country of the document.
    */
    'issuingCountry': string | null;
    /**
    * Last name as it appears in the document.
    */
    'lastName': string | null;
    /**
    * Document ID number.
    */
    'number': string | null;
    /**
    * Status of this `document` check.
    */
    'status': GelatoDocumentReport.StatusEnum;
    /**
    * Type of the document.
    */
    'type': GelatoDocumentReport.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "GelatoDocumentReportAddress"
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "GelatoDocumentReportDob"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "GelatoDocumentReportError1"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "GelatoDocumentReportExpirationDate"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<string>"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "issuedDate",
            "baseName": "issued_date",
            "type": "GelatoDocumentReportIssuedDate"
        },
        {
            "name": "issuingCountry",
            "baseName": "issuing_country",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GelatoDocumentReport.StatusEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GelatoDocumentReport.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return GelatoDocumentReport.attributeTypeMap;
    }
}

export namespace GelatoDocumentReport {
    export enum StatusEnum {
        Unverified = <any> 'unverified',
        Verified = <any> 'verified'
    }
    export enum TypeEnum {
        DrivingLicense = <any> 'driving_license',
        IdCard = <any> 'id_card',
        Passport = <any> 'passport'
    }
}
