/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreditNoteTaxAmountTaxRate } from './creditNoteTaxAmountTaxRate';

/**
* 
*/
export class InvoiceTaxAmount {
    /**
    * The amount, in %s, of the tax.
    */
    'amount': number;
    /**
    * Whether this tax amount is inclusive or exclusive.
    */
    'inclusive': boolean;
    'taxRate': CreditNoteTaxAmountTaxRate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "inclusive",
            "baseName": "inclusive",
            "type": "boolean"
        },
        {
            "name": "taxRate",
            "baseName": "tax_rate",
            "type": "CreditNoteTaxAmountTaxRate"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceTaxAmount.attributeTypeMap;
    }
}

