/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiErrors } from './apiErrors';
import { PaymentIntent } from './paymentIntent';
import { PaymentMethod } from './paymentMethod';
import { PaymentSource } from './paymentSource';
import { SetupIntent } from './setupIntent';

/**
* The error encountered during the previous attempt to finalize the invoice. This field is cleared when the invoice is successfully finalized.
*/
export class InvoiceLastFinalizationError {
    /**
    * For card errors, the ID of the failed charge.
    */
    'charge'?: string;
    /**
    * For some errors that could be handled programmatically, a short string indicating the [error code](https://stripe.com/docs/error-codes) reported.
    */
    'code'?: string;
    /**
    * For card errors resulting from a card issuer decline, a short string indicating the [card issuer\'s reason for the decline](https://stripe.com/docs/declines#issuer-declines) if they provide one.
    */
    'declineCode'?: string;
    /**
    * A URL to more information about the [error code](https://stripe.com/docs/error-codes) reported.
    */
    'docUrl'?: string;
    /**
    * A human-readable message providing more details about the error. For card errors, these messages can be shown to your users.
    */
    'message'?: string;
    /**
    * If the error is parameter-specific, the parameter related to the error. For example, you can use this to display a message near the correct form field.
    */
    'param'?: string;
    'paymentIntent'?: PaymentIntent;
    'paymentMethod'?: PaymentMethod;
    /**
    * If the error is specific to the type of payment method, the payment method type that had a problem. This field is only populated for invoice-related errors.
    */
    'paymentMethodType'?: string;
    /**
    * A URL to the request log entry in your dashboard.
    */
    'requestLogUrl'?: string;
    'setupIntent'?: SetupIntent;
    'source'?: PaymentSource;
    /**
    * The type of error returned. One of `api_error`, `card_error`, `idempotency_error`, or `invalid_request_error`
    */
    'type': InvoiceLastFinalizationError.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "charge",
            "baseName": "charge",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "declineCode",
            "baseName": "decline_code",
            "type": "string"
        },
        {
            "name": "docUrl",
            "baseName": "doc_url",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "param",
            "baseName": "param",
            "type": "string"
        },
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "PaymentIntent"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "PaymentMethod"
        },
        {
            "name": "paymentMethodType",
            "baseName": "payment_method_type",
            "type": "string"
        },
        {
            "name": "requestLogUrl",
            "baseName": "request_log_url",
            "type": "string"
        },
        {
            "name": "setupIntent",
            "baseName": "setup_intent",
            "type": "SetupIntent"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "PaymentSource"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "InvoiceLastFinalizationError.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceLastFinalizationError.attributeTypeMap;
    }
}

export namespace InvoiceLastFinalizationError {
    export enum TypeEnum {
        ApiError = <any> 'api_error',
        CardError = <any> 'card_error',
        IdempotencyError = <any> 'idempotency_error',
        InvalidRequestError = <any> 'invalid_request_error'
    }
}
