/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoicesLineItemsCreditedItems } from './invoicesLineItemsCreditedItems';

/**
* For a credit proration `line_item`, the original debit line_items to which the credit proration applies.
*/
export class InvoicesLineItemsProrationDetailsCreditedItems {
    /**
    * Invoice containing the credited invoice line items
    */
    'invoice': string;
    /**
    * Credited invoice line items
    */
    'invoiceLineItems': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "string"
        },
        {
            "name": "invoiceLineItems",
            "baseName": "invoice_line_items",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return InvoicesLineItemsProrationDetailsCreditedItems.attributeTypeMap;
    }
}

