/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer } from './invoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer';

/**
* 
*/
export class InvoicePaymentMethodOptionsCustomerBalanceBankTransfer {
    'euBankTransfer'?: InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer;
    /**
    * The bank transfer type that can be used for funding. Permitted values include: `eu_bank_transfer`, `gb_bank_transfer`, `jp_bank_transfer`, or `mx_bank_transfer`.
    */
    'type': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "euBankTransfer",
            "baseName": "eu_bank_transfer",
            "type": "InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoicePaymentMethodOptionsCustomerBalanceBankTransfer.attributeTypeMap;
    }
}

