/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class InvoicesResourceInvoiceTaxId {
    /**
    * The type of the tax ID, one of `eu_vat`, `br_cnpj`, `br_cpf`, `eu_oss_vat`, `gb_vat`, `nz_gst`, `au_abn`, `au_arn`, `in_gst`, `no_vat`, `za_vat`, `ch_vat`, `mx_rfc`, `sg_uen`, `ru_inn`, `ru_kpp`, `ca_bn`, `hk_br`, `es_cif`, `tw_vat`, `th_vat`, `jp_cn`, `jp_rn`, `jp_trn`, `li_uid`, `my_itn`, `us_ein`, `kr_brn`, `ca_qst`, `ca_gst_hst`, `ca_pst_bc`, `ca_pst_mb`, `ca_pst_sk`, `my_sst`, `sg_gst`, `ae_trn`, `cl_tin`, `sa_vat`, `id_npwp`, `my_frp`, `il_vat`, `ge_vat`, `ua_vat`, `is_vat`, `bg_uic`, `hu_tin`, `si_tin`, `ke_pin`, `tr_tin`, `eg_tin`, `ph_tin`, or `unknown`
    */
    'type': InvoicesResourceInvoiceTaxId.TypeEnum;
    /**
    * The value of the tax ID.
    */
    'value': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InvoicesResourceInvoiceTaxId.TypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoicesResourceInvoiceTaxId.attributeTypeMap;
    }
}

export namespace InvoicesResourceInvoiceTaxId {
    export enum TypeEnum {
        AeTrn = <any> 'ae_trn',
        AuAbn = <any> 'au_abn',
        AuArn = <any> 'au_arn',
        BgUic = <any> 'bg_uic',
        BrCnpj = <any> 'br_cnpj',
        BrCpf = <any> 'br_cpf',
        CaBn = <any> 'ca_bn',
        CaGstHst = <any> 'ca_gst_hst',
        CaPstBc = <any> 'ca_pst_bc',
        CaPstMb = <any> 'ca_pst_mb',
        CaPstSk = <any> 'ca_pst_sk',
        CaQst = <any> 'ca_qst',
        ChVat = <any> 'ch_vat',
        ClTin = <any> 'cl_tin',
        EgTin = <any> 'eg_tin',
        EsCif = <any> 'es_cif',
        EuOssVat = <any> 'eu_oss_vat',
        EuVat = <any> 'eu_vat',
        GbVat = <any> 'gb_vat',
        GeVat = <any> 'ge_vat',
        HkBr = <any> 'hk_br',
        HuTin = <any> 'hu_tin',
        IdNpwp = <any> 'id_npwp',
        IlVat = <any> 'il_vat',
        InGst = <any> 'in_gst',
        IsVat = <any> 'is_vat',
        JpCn = <any> 'jp_cn',
        JpRn = <any> 'jp_rn',
        JpTrn = <any> 'jp_trn',
        KePin = <any> 'ke_pin',
        KrBrn = <any> 'kr_brn',
        LiUid = <any> 'li_uid',
        MxRfc = <any> 'mx_rfc',
        MyFrp = <any> 'my_frp',
        MyItn = <any> 'my_itn',
        MySst = <any> 'my_sst',
        NoVat = <any> 'no_vat',
        NzGst = <any> 'nz_gst',
        PhTin = <any> 'ph_tin',
        RuInn = <any> 'ru_inn',
        RuKpp = <any> 'ru_kpp',
        SaVat = <any> 'sa_vat',
        SgGst = <any> 'sg_gst',
        SgUen = <any> 'sg_uen',
        SiTin = <any> 'si_tin',
        ThVat = <any> 'th_vat',
        TrTin = <any> 'tr_tin',
        TwVat = <any> 'tw_vat',
        UaVat = <any> 'ua_vat',
        Unknown = <any> 'unknown',
        UsEin = <any> 'us_ein',
        ZaVat = <any> 'za_vat'
    }
}
