/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceItemThresholdReason } from './invoiceItemThresholdReason';

/**
* 
*/
export class InvoiceThresholdReason {
    /**
    * The total invoice amount threshold boundary if it triggered the threshold invoice.
    */
    'amountGte': number | null;
    /**
    * Indicates which line items triggered a threshold invoice.
    */
    'itemReasons': Array<InvoiceItemThresholdReason>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountGte",
            "baseName": "amount_gte",
            "type": "number"
        },
        {
            "name": "itemReasons",
            "baseName": "item_reasons",
            "type": "Array<InvoiceItemThresholdReason>"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceThresholdReason.attributeTypeMap;
    }
}

