/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceSettingRenderingOptions } from './invoiceSettingRenderingOptions';

/**
* Options for invoice PDF rendering.
*/
export class InvoiceRenderingOptions {
    /**
    * How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
    */
    'amountTaxDisplay': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountTaxDisplay",
            "baseName": "amount_tax_display",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceRenderingOptions.attributeTypeMap;
    }
}

