/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions {
    /**
    * The list of permissions to request. The `payment_method` permission must be included.
    */
    'permissions'?: Array<InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions.PermissionsEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions.PermissionsEnum>"
        }    ];

    static getAttributeTypeMap() {
        return InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions.attributeTypeMap;
    }
}

export namespace InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions {
    export enum PermissionsEnum {
        Balances = <any> 'balances',
        PaymentMethod = <any> 'payment_method',
        Transactions = <any> 'transactions'
    }
}
