/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceitemDiscountsInner } from './invoiceitemDiscountsInner';
import { PaymentLinkOnBehalfOf } from './paymentLinkOnBehalfOf';
import { Quote } from './quote';
import { QuoteApplication } from './quoteApplication';
import { QuoteCustomer } from './quoteCustomer';
import { QuoteDefaultTaxRatesInner } from './quoteDefaultTaxRatesInner';
import { QuoteFromQuote } from './quoteFromQuote';
import { QuoteInvoice } from './quoteInvoice';
import { QuoteInvoiceSettings } from './quoteInvoiceSettings';
import { QuoteSubscription } from './quoteSubscription';
import { QuoteSubscriptionSchedule } from './quoteSubscriptionSchedule';
import { QuoteTestClock } from './quoteTestClock';
import { QuoteTransferData } from './quoteTransferData';
import { QuotesResourceAutomaticTax } from './quotesResourceAutomaticTax';
import { QuotesResourceComputed } from './quotesResourceComputed';
import { QuotesResourceListLineItems1 } from './quotesResourceListLineItems1';
import { QuotesResourceStatusTransitions } from './quotesResourceStatusTransitions';
import { QuotesResourceSubscriptionDataSubscriptionData } from './quotesResourceSubscriptionDataSubscriptionData';
import { QuotesResourceTotalDetails } from './quotesResourceTotalDetails';

/**
* The quote this invoice was generated from.
*/
export class InvoiceQuote {
    /**
    * Total before any discounts or taxes are applied.
    */
    'amountSubtotal': number;
    /**
    * Total after discounts and taxes are applied.
    */
    'amountTotal': number;
    'application': QuoteApplication | null;
    /**
    * The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner\'s Stripe account. Only applicable if there are no line items with recurring prices on the quote.
    */
    'applicationFeeAmount': number | null;
    /**
    * A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the application owner\'s Stripe account. Only applicable if there are line items with recurring prices on the quote.
    */
    'applicationFeePercent': number | null;
    'automaticTax': QuotesResourceAutomaticTax;
    /**
    * Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay invoices at the end of the subscription cycle or on finalization using the default payment method attached to the subscription or customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`. Defaults to `charge_automatically`.
    */
    'collectionMethod': InvoiceQuote.CollectionMethodEnum;
    'computed': QuotesResourceComputed;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string | null;
    'customer': QuoteCustomer | null;
    /**
    * The tax rates applied to this quote.
    */
    'defaultTaxRates'?: Array<QuoteDefaultTaxRatesInner>;
    /**
    * A description that will be displayed on the quote PDF.
    */
    'description': string | null;
    /**
    * The discounts applied to this quote.
    */
    'discounts': Array<InvoiceitemDiscountsInner>;
    /**
    * The date on which the quote will be canceled if in `open` or `draft` status. Measured in seconds since the Unix epoch.
    */
    'expiresAt': number;
    /**
    * A footer that will be displayed on the quote PDF.
    */
    'footer': string | null;
    'fromQuote': QuoteFromQuote | null;
    /**
    * A header that will be displayed on the quote PDF.
    */
    'header': string | null;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    'invoice': QuoteInvoice | null;
    'invoiceSettings': QuoteInvoiceSettings | null;
    'lineItems'?: QuotesResourceListLineItems1;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; };
    /**
    * A unique number that identifies this particular quote. This number is assigned once the quote is [finalized](https://stripe.com/docs/quotes/overview#finalize).
    */
    'number': string | null;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': InvoiceQuote.ObjectEnum;
    'onBehalfOf': PaymentLinkOnBehalfOf | null;
    /**
    * The status of the quote.
    */
    'status': InvoiceQuote.StatusEnum;
    'statusTransitions': QuotesResourceStatusTransitions;
    'subscription': QuoteSubscription | null;
    'subscriptionData': QuotesResourceSubscriptionDataSubscriptionData;
    'subscriptionSchedule': QuoteSubscriptionSchedule | null;
    'testClock': QuoteTestClock | null;
    'totalDetails': QuotesResourceTotalDetails;
    'transferData': QuoteTransferData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountSubtotal",
            "baseName": "amount_subtotal",
            "type": "number"
        },
        {
            "name": "amountTotal",
            "baseName": "amount_total",
            "type": "number"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "QuoteApplication"
        },
        {
            "name": "applicationFeeAmount",
            "baseName": "application_fee_amount",
            "type": "number"
        },
        {
            "name": "applicationFeePercent",
            "baseName": "application_fee_percent",
            "type": "number"
        },
        {
            "name": "automaticTax",
            "baseName": "automatic_tax",
            "type": "QuotesResourceAutomaticTax"
        },
        {
            "name": "collectionMethod",
            "baseName": "collection_method",
            "type": "InvoiceQuote.CollectionMethodEnum"
        },
        {
            "name": "computed",
            "baseName": "computed",
            "type": "QuotesResourceComputed"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "QuoteCustomer"
        },
        {
            "name": "defaultTaxRates",
            "baseName": "default_tax_rates",
            "type": "Array<QuoteDefaultTaxRatesInner>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Array<InvoiceitemDiscountsInner>"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "footer",
            "baseName": "footer",
            "type": "string"
        },
        {
            "name": "fromQuote",
            "baseName": "from_quote",
            "type": "QuoteFromQuote"
        },
        {
            "name": "header",
            "baseName": "header",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "QuoteInvoice"
        },
        {
            "name": "invoiceSettings",
            "baseName": "invoice_settings",
            "type": "QuoteInvoiceSettings"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "QuotesResourceListLineItems1"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "InvoiceQuote.ObjectEnum"
        },
        {
            "name": "onBehalfOf",
            "baseName": "on_behalf_of",
            "type": "PaymentLinkOnBehalfOf"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InvoiceQuote.StatusEnum"
        },
        {
            "name": "statusTransitions",
            "baseName": "status_transitions",
            "type": "QuotesResourceStatusTransitions"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "QuoteSubscription"
        },
        {
            "name": "subscriptionData",
            "baseName": "subscription_data",
            "type": "QuotesResourceSubscriptionDataSubscriptionData"
        },
        {
            "name": "subscriptionSchedule",
            "baseName": "subscription_schedule",
            "type": "QuoteSubscriptionSchedule"
        },
        {
            "name": "testClock",
            "baseName": "test_clock",
            "type": "QuoteTestClock"
        },
        {
            "name": "totalDetails",
            "baseName": "total_details",
            "type": "QuotesResourceTotalDetails"
        },
        {
            "name": "transferData",
            "baseName": "transfer_data",
            "type": "QuoteTransferData"
        }    ];

    static getAttributeTypeMap() {
        return InvoiceQuote.attributeTypeMap;
    }
}

export namespace InvoiceQuote {
    export enum CollectionMethodEnum {
        ChargeAutomatically = <any> 'charge_automatically',
        SendInvoice = <any> 'send_invoice'
    }
    export enum ObjectEnum {
        Quote = <any> 'quote'
    }
    export enum StatusEnum {
        Accepted = <any> 'accepted',
        Canceled = <any> 'canceled',
        Draft = <any> 'draft',
        Open = <any> 'open'
    }
}
