/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoicesFromInvoiceInvoice } from './invoicesFromInvoiceInvoice';

/**
* 
*/
export class InvoicesFromInvoice {
    /**
    * The relation between this invoice and the cloned invoice
    */
    'action': string;
    'invoice': InvoicesFromInvoiceInvoice;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "InvoicesFromInvoiceInvoice"
        }    ];

    static getAttributeTypeMap() {
        return InvoicesFromInvoice.attributeTypeMap;
    }
}

