/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingTransactionTreasury } from './issuingTransactionTreasury';

/**
* [Treasury](https://stripe.com/docs/api/treasury) details related to this transaction if it was created on a [FinancialAccount](/docs/api/treasury/financial_accounts
*/
export class IssuingTransactionTreasury1 {
    /**
    * The Treasury [ReceivedCredit](https://stripe.com/docs/api/treasury/received_credits) representing this Issuing transaction if it is a refund
    */
    'receivedCredit': string | null;
    /**
    * The Treasury [ReceivedDebit](https://stripe.com/docs/api/treasury/received_debits) representing this Issuing transaction if it is a capture
    */
    'receivedDebit': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "receivedCredit",
            "baseName": "received_credit",
            "type": "string"
        },
        {
            "name": "receivedDebit",
            "baseName": "received_debit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssuingTransactionTreasury1.attributeTypeMap;
    }
}

