/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingCardholderCompany } from './issuingCardholderCompany';

/**
* Additional information about a `company` cardholder.
*/
export class IssuingCardholderCompany1 {
    /**
    * Whether the company\'s business ID number was provided.
    */
    'taxIdProvided': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taxIdProvided",
            "baseName": "tax_id_provided",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return IssuingCardholderCompany1.attributeTypeMap;
    }
}

