/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BalanceTransaction } from './balanceTransaction';
import { IssuingDispute } from './issuingDispute';
import { IssuingDisputeEvidence } from './issuingDisputeEvidence';
import { IssuingDisputeTransaction } from './issuingDisputeTransaction';
import { IssuingDisputeTreasury1 } from './issuingDisputeTreasury1';

/**
* If you\'ve disputed the transaction, the ID of the dispute.
*/
export class IssuingTransactionDispute {
    /**
    * Disputed amount in the card\'s currency and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal). Usually the amount of the `transaction`, but can differ (usually because of currency fluctuation).
    */
    'amount': number;
    /**
    * List of balance transactions associated with the dispute.
    */
    'balanceTransactions': Array<BalanceTransaction> | null;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * The currency the `transaction` was made in.
    */
    'currency': string;
    'evidence': IssuingDisputeEvidence;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata': { [key: string]: string; };
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': IssuingTransactionDispute.ObjectEnum;
    /**
    * Current status of the dispute.
    */
    'status': IssuingTransactionDispute.StatusEnum;
    'transaction': IssuingDisputeTransaction;
    'treasury'?: IssuingDisputeTreasury1 | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "balanceTransactions",
            "baseName": "balance_transactions",
            "type": "Array<BalanceTransaction>"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "evidence",
            "baseName": "evidence",
            "type": "IssuingDisputeEvidence"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "IssuingTransactionDispute.ObjectEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "IssuingTransactionDispute.StatusEnum"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "IssuingDisputeTransaction"
        },
        {
            "name": "treasury",
            "baseName": "treasury",
            "type": "IssuingDisputeTreasury1"
        }    ];

    static getAttributeTypeMap() {
        return IssuingTransactionDispute.attributeTypeMap;
    }
}

export namespace IssuingTransactionDispute {
    export enum ObjectEnum {
        IssuingDispute = <any> 'issuing.dispute'
    }
    export enum StatusEnum {
        Expired = <any> 'expired',
        Lost = <any> 'lost',
        Submitted = <any> 'submitted',
        Unsubmitted = <any> 'unsubmitted',
        Won = <any> 'won'
    }
}
