/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingDisputeCanceledEvidenceAdditionalDocumentation } from './issuingDisputeCanceledEvidenceAdditionalDocumentation';

/**
* 
*/
export class IssuingDisputeOtherEvidence {
    'additionalDocumentation': IssuingDisputeCanceledEvidenceAdditionalDocumentation | null;
    /**
    * Explanation of why the cardholder is disputing this transaction.
    */
    'explanation': string | null;
    /**
    * Description of the merchandise or service that was purchased.
    */
    'productDescription': string | null;
    /**
    * Whether the product was a merchandise or service.
    */
    'productType': IssuingDisputeOtherEvidence.ProductTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalDocumentation",
            "baseName": "additional_documentation",
            "type": "IssuingDisputeCanceledEvidenceAdditionalDocumentation"
        },
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "string"
        },
        {
            "name": "productDescription",
            "baseName": "product_description",
            "type": "string"
        },
        {
            "name": "productType",
            "baseName": "product_type",
            "type": "IssuingDisputeOtherEvidence.ProductTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return IssuingDisputeOtherEvidence.attributeTypeMap;
    }
}

export namespace IssuingDisputeOtherEvidence {
    export enum ProductTypeEnum {
        Merchandise = <any> 'merchandise',
        Service = <any> 'service'
    }
}
