/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class IssuingAuthorizationVerificationData {
    /**
    * Whether the cardholder provided an address first line and if it matched the cardholder’s `billing.address.line1`.
    */
    'addressLine1Check': IssuingAuthorizationVerificationData.AddressLine1CheckEnum;
    /**
    * Whether the cardholder provided a postal code and if it matched the cardholder’s `billing.address.postal_code`.
    */
    'addressPostalCodeCheck': IssuingAuthorizationVerificationData.AddressPostalCodeCheckEnum;
    /**
    * Whether the cardholder provided a CVC and if it matched Stripe’s record.
    */
    'cvcCheck': IssuingAuthorizationVerificationData.CvcCheckEnum;
    /**
    * Whether the cardholder provided an expiry date and if it matched Stripe’s record.
    */
    'expiryCheck': IssuingAuthorizationVerificationData.ExpiryCheckEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addressLine1Check",
            "baseName": "address_line1_check",
            "type": "IssuingAuthorizationVerificationData.AddressLine1CheckEnum"
        },
        {
            "name": "addressPostalCodeCheck",
            "baseName": "address_postal_code_check",
            "type": "IssuingAuthorizationVerificationData.AddressPostalCodeCheckEnum"
        },
        {
            "name": "cvcCheck",
            "baseName": "cvc_check",
            "type": "IssuingAuthorizationVerificationData.CvcCheckEnum"
        },
        {
            "name": "expiryCheck",
            "baseName": "expiry_check",
            "type": "IssuingAuthorizationVerificationData.ExpiryCheckEnum"
        }    ];

    static getAttributeTypeMap() {
        return IssuingAuthorizationVerificationData.attributeTypeMap;
    }
}

export namespace IssuingAuthorizationVerificationData {
    export enum AddressLine1CheckEnum {
        Match = <any> 'match',
        Mismatch = <any> 'mismatch',
        NotProvided = <any> 'not_provided'
    }
    export enum AddressPostalCodeCheckEnum {
        Match = <any> 'match',
        Mismatch = <any> 'mismatch',
        NotProvided = <any> 'not_provided'
    }
    export enum CvcCheckEnum {
        Match = <any> 'match',
        Mismatch = <any> 'mismatch',
        NotProvided = <any> 'not_provided'
    }
    export enum ExpiryCheckEnum {
        Match = <any> 'match',
        Mismatch = <any> 'mismatch',
        NotProvided = <any> 'not_provided'
    }
}
