/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingTransactionFlightData } from './issuingTransactionFlightData';
import { IssuingTransactionFlightDataLeg } from './issuingTransactionFlightDataLeg';

/**
* Information about the flight that was purchased with this transaction.
*/
export class IssuingTransactionPurchaseDetailsFlight {
    /**
    * The time that the flight departed.
    */
    'departureAt': number | null;
    /**
    * The name of the passenger.
    */
    'passengerName': string | null;
    /**
    * Whether the ticket is refundable.
    */
    'refundable': boolean | null;
    /**
    * The legs of the trip.
    */
    'segments': Array<IssuingTransactionFlightDataLeg> | null;
    /**
    * The travel agency that issued the ticket.
    */
    'travelAgency': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "departureAt",
            "baseName": "departure_at",
            "type": "number"
        },
        {
            "name": "passengerName",
            "baseName": "passenger_name",
            "type": "string"
        },
        {
            "name": "refundable",
            "baseName": "refundable",
            "type": "boolean"
        },
        {
            "name": "segments",
            "baseName": "segments",
            "type": "Array<IssuingTransactionFlightDataLeg>"
        },
        {
            "name": "travelAgency",
            "baseName": "travel_agency",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssuingTransactionPurchaseDetailsFlight.attributeTypeMap;
    }
}

