/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class IssuingCardGooglePay {
    /**
    * Google Pay Eligibility
    */
    'eligible': boolean;
    /**
    * Reason the card is ineligible for Google Pay
    */
    'ineligibleReason': IssuingCardGooglePay.IneligibleReasonEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eligible",
            "baseName": "eligible",
            "type": "boolean"
        },
        {
            "name": "ineligibleReason",
            "baseName": "ineligible_reason",
            "type": "IssuingCardGooglePay.IneligibleReasonEnum"
        }    ];

    static getAttributeTypeMap() {
        return IssuingCardGooglePay.attributeTypeMap;
    }
}

export namespace IssuingCardGooglePay {
    export enum IneligibleReasonEnum {
        MissingAgreement = <any> 'missing_agreement',
        MissingCardholderContact = <any> 'missing_cardholder_contact',
        UnsupportedRegion = <any> 'unsupported_region'
    }
}
