/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingDisputeCanceledEvidenceAdditionalDocumentation } from './issuingDisputeCanceledEvidenceAdditionalDocumentation';

/**
* 
*/
export class IssuingDisputeCanceledEvidence {
    'additionalDocumentation': IssuingDisputeCanceledEvidenceAdditionalDocumentation | null;
    /**
    * Date when order was canceled.
    */
    'canceledAt': number | null;
    /**
    * Whether the cardholder was provided with a cancellation policy.
    */
    'cancellationPolicyProvided': boolean | null;
    /**
    * Reason for canceling the order.
    */
    'cancellationReason': string | null;
    /**
    * Date when the cardholder expected to receive the product.
    */
    'expectedAt': number | null;
    /**
    * Explanation of why the cardholder is disputing this transaction.
    */
    'explanation': string | null;
    /**
    * Description of the merchandise or service that was purchased.
    */
    'productDescription': string | null;
    /**
    * Whether the product was a merchandise or service.
    */
    'productType': IssuingDisputeCanceledEvidence.ProductTypeEnum;
    /**
    * Result of cardholder\'s attempt to return the product.
    */
    'returnStatus': IssuingDisputeCanceledEvidence.ReturnStatusEnum;
    /**
    * Date when the product was returned or attempted to be returned.
    */
    'returnedAt': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalDocumentation",
            "baseName": "additional_documentation",
            "type": "IssuingDisputeCanceledEvidenceAdditionalDocumentation"
        },
        {
            "name": "canceledAt",
            "baseName": "canceled_at",
            "type": "number"
        },
        {
            "name": "cancellationPolicyProvided",
            "baseName": "cancellation_policy_provided",
            "type": "boolean"
        },
        {
            "name": "cancellationReason",
            "baseName": "cancellation_reason",
            "type": "string"
        },
        {
            "name": "expectedAt",
            "baseName": "expected_at",
            "type": "number"
        },
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "string"
        },
        {
            "name": "productDescription",
            "baseName": "product_description",
            "type": "string"
        },
        {
            "name": "productType",
            "baseName": "product_type",
            "type": "IssuingDisputeCanceledEvidence.ProductTypeEnum"
        },
        {
            "name": "returnStatus",
            "baseName": "return_status",
            "type": "IssuingDisputeCanceledEvidence.ReturnStatusEnum"
        },
        {
            "name": "returnedAt",
            "baseName": "returned_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IssuingDisputeCanceledEvidence.attributeTypeMap;
    }
}

export namespace IssuingDisputeCanceledEvidence {
    export enum ProductTypeEnum {
        Merchandise = <any> 'merchandise',
        Service = <any> 'service'
    }
    export enum ReturnStatusEnum {
        MerchantRejected = <any> 'merchant_rejected',
        Successful = <any> 'successful'
    }
}
