/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class IssuingTransactionFlightDataLeg {
    /**
    * The three-letter IATA airport code of the flight\'s destination.
    */
    'arrivalAirportCode': string | null;
    /**
    * The airline carrier code.
    */
    'carrier': string | null;
    /**
    * The three-letter IATA airport code that the flight departed from.
    */
    'departureAirportCode': string | null;
    /**
    * The flight number.
    */
    'flightNumber': string | null;
    /**
    * The flight\'s service class.
    */
    'serviceClass': string | null;
    /**
    * Whether a stopover is allowed on this flight.
    */
    'stopoverAllowed': boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "arrivalAirportCode",
            "baseName": "arrival_airport_code",
            "type": "string"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "departureAirportCode",
            "baseName": "departure_airport_code",
            "type": "string"
        },
        {
            "name": "flightNumber",
            "baseName": "flight_number",
            "type": "string"
        },
        {
            "name": "serviceClass",
            "baseName": "service_class",
            "type": "string"
        },
        {
            "name": "stopoverAllowed",
            "baseName": "stopover_allowed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return IssuingTransactionFlightDataLeg.attributeTypeMap;
    }
}

