/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingDisputeCanceledEvidenceAdditionalDocumentation } from './issuingDisputeCanceledEvidenceAdditionalDocumentation';

/**
* 
*/
export class IssuingDisputeMerchandiseNotAsDescribedEvidence {
    'additionalDocumentation': IssuingDisputeCanceledEvidenceAdditionalDocumentation | null;
    /**
    * Explanation of why the cardholder is disputing this transaction.
    */
    'explanation': string | null;
    /**
    * Date when the product was received.
    */
    'receivedAt': number | null;
    /**
    * Description of the cardholder\'s attempt to return the product.
    */
    'returnDescription': string | null;
    /**
    * Result of cardholder\'s attempt to return the product.
    */
    'returnStatus': IssuingDisputeMerchandiseNotAsDescribedEvidence.ReturnStatusEnum;
    /**
    * Date when the product was returned or attempted to be returned.
    */
    'returnedAt': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalDocumentation",
            "baseName": "additional_documentation",
            "type": "IssuingDisputeCanceledEvidenceAdditionalDocumentation"
        },
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "string"
        },
        {
            "name": "receivedAt",
            "baseName": "received_at",
            "type": "number"
        },
        {
            "name": "returnDescription",
            "baseName": "return_description",
            "type": "string"
        },
        {
            "name": "returnStatus",
            "baseName": "return_status",
            "type": "IssuingDisputeMerchandiseNotAsDescribedEvidence.ReturnStatusEnum"
        },
        {
            "name": "returnedAt",
            "baseName": "returned_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IssuingDisputeMerchandiseNotAsDescribedEvidence.attributeTypeMap;
    }
}

export namespace IssuingDisputeMerchandiseNotAsDescribedEvidence {
    export enum ReturnStatusEnum {
        MerchantRejected = <any> 'merchant_rejected',
        Successful = <any> 'successful'
    }
}
