/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PaymentIntentNextActionBoleto {
    /**
    * The timestamp after which the boleto expires.
    */
    'expiresAt': number | null;
    /**
    * The URL to the hosted boleto voucher page, which allows customers to view the boleto voucher.
    */
    'hostedVoucherUrl': string | null;
    /**
    * The boleto number.
    */
    'number': string | null;
    /**
    * The URL to the downloadable boleto voucher PDF.
    */
    'pdf': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "hostedVoucherUrl",
            "baseName": "hosted_voucher_url",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "pdf",
            "baseName": "pdf",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentIntentNextActionBoleto.attributeTypeMap;
    }
}

