/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FundingInstructionsBankTransferFinancialAddress } from './fundingInstructionsBankTransferFinancialAddress';

/**
* 
*/
export class PaymentIntentNextActionDisplayBankTransferInstructions {
    /**
    * The remaining amount that needs to be transferred to complete the payment.
    */
    'amountRemaining': number | null;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string | null;
    /**
    * A list of financial addresses that can be used to fund the customer balance
    */
    'financialAddresses'?: Array<FundingInstructionsBankTransferFinancialAddress>;
    /**
    * A link to a hosted page that guides your customer through completing the transfer.
    */
    'hostedInstructionsUrl': string | null;
    /**
    * A string identifying this payment. Instruct your customer to include this code in the reference or memo field of their bank transfer.
    */
    'reference': string | null;
    /**
    * Type of bank transfer
    */
    'type': PaymentIntentNextActionDisplayBankTransferInstructions.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountRemaining",
            "baseName": "amount_remaining",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "financialAddresses",
            "baseName": "financial_addresses",
            "type": "Array<FundingInstructionsBankTransferFinancialAddress>"
        },
        {
            "name": "hostedInstructionsUrl",
            "baseName": "hosted_instructions_url",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentIntentNextActionDisplayBankTransferInstructions.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PaymentIntentNextActionDisplayBankTransferInstructions.attributeTypeMap;
    }
}

export namespace PaymentIntentNextActionDisplayBankTransferInstructions {
    export enum TypeEnum {
        EuBankTransfer = <any> 'eu_bank_transfer',
        GbBankTransfer = <any> 'gb_bank_transfer',
        JpBankTransfer = <any> 'jp_bank_transfer',
        MxBankTransfer = <any> 'mx_bank_transfer'
    }
}
