/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentIntentNextActionKonbiniStores } from './paymentIntentNextActionKonbiniStores';

/**
* 
*/
export class PaymentIntentNextActionKonbini {
    /**
    * The timestamp at which the pending Konbini payment expires.
    */
    'expiresAt': number;
    /**
    * The URL for the Konbini payment instructions page, which allows customers to view and print a Konbini voucher.
    */
    'hostedVoucherUrl': string | null;
    'stores': PaymentIntentNextActionKonbiniStores;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "hostedVoucherUrl",
            "baseName": "hosted_voucher_url",
            "type": "string"
        },
        {
            "name": "stores",
            "baseName": "stores",
            "type": "PaymentIntentNextActionKonbiniStores"
        }    ];

    static getAttributeTypeMap() {
        return PaymentIntentNextActionKonbini.attributeTypeMap;
    }
}

