/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodDetailsBancontactGeneratedSepaDebit } from './paymentMethodDetailsBancontactGeneratedSepaDebit';
import { PaymentMethodDetailsBancontactGeneratedSepaDebitMandate } from './paymentMethodDetailsBancontactGeneratedSepaDebitMandate';

/**
* 
*/
export class PaymentMethodDetailsSofort {
    /**
    * Bank code of bank associated with the bank account.
    */
    'bankCode': string | null;
    /**
    * Name of the bank associated with the bank account.
    */
    'bankName': string | null;
    /**
    * Bank Identifier Code of the bank associated with the bank account.
    */
    'bic': string | null;
    /**
    * Two-letter ISO code representing the country the bank account is located in.
    */
    'country': string | null;
    'generatedSepaDebit': PaymentMethodDetailsBancontactGeneratedSepaDebit | null;
    'generatedSepaDebitMandate': PaymentMethodDetailsBancontactGeneratedSepaDebitMandate | null;
    /**
    * Last four characters of the IBAN.
    */
    'ibanLast4': string | null;
    /**
    * Preferred language of the SOFORT authorization page that the customer is redirected to. Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
    */
    'preferredLanguage': PaymentMethodDetailsSofort.PreferredLanguageEnum;
    /**
    * Owner\'s verified full name. Values are verified or provided by SOFORT directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'verifiedName': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bankCode",
            "baseName": "bank_code",
            "type": "string"
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string"
        },
        {
            "name": "bic",
            "baseName": "bic",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "generatedSepaDebit",
            "baseName": "generated_sepa_debit",
            "type": "PaymentMethodDetailsBancontactGeneratedSepaDebit"
        },
        {
            "name": "generatedSepaDebitMandate",
            "baseName": "generated_sepa_debit_mandate",
            "type": "PaymentMethodDetailsBancontactGeneratedSepaDebitMandate"
        },
        {
            "name": "ibanLast4",
            "baseName": "iban_last4",
            "type": "string"
        },
        {
            "name": "preferredLanguage",
            "baseName": "preferred_language",
            "type": "PaymentMethodDetailsSofort.PreferredLanguageEnum"
        },
        {
            "name": "verifiedName",
            "baseName": "verified_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsSofort.attributeTypeMap;
    }
}

export namespace PaymentMethodDetailsSofort {
    export enum PreferredLanguageEnum {
        De = <any> 'de',
        En = <any> 'en',
        Es = <any> 'es',
        Fr = <any> 'fr',
        It = <any> 'it',
        Nl = <any> 'nl',
        Pl = <any> 'pl'
    }
}
