/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodDetailsCardWalletMasterpass } from './paymentMethodDetailsCardWalletMasterpass';
import { PaymentMethodDetailsCardWalletVisaCheckout } from './paymentMethodDetailsCardWalletVisaCheckout';

/**
* 
*/
export class PaymentMethodDetailsCardWallet {
    /**
    * 
    */
    'amexExpressCheckout'?: object;
    /**
    * 
    */
    'applePay'?: object;
    /**
    * (For tokenized numbers only.) The last four digits of the device account number.
    */
    'dynamicLast4': string | null;
    /**
    * 
    */
    'googlePay'?: object;
    'masterpass'?: PaymentMethodDetailsCardWalletMasterpass;
    /**
    * 
    */
    'samsungPay'?: object;
    /**
    * The type of the card wallet, one of `amex_express_checkout`, `apple_pay`, `google_pay`, `masterpass`, `samsung_pay`, or `visa_checkout`. An additional hash is included on the Wallet subhash with a name matching this value. It contains additional information specific to the card wallet type.
    */
    'type': PaymentMethodDetailsCardWallet.TypeEnum;
    'visaCheckout'?: PaymentMethodDetailsCardWalletVisaCheckout;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amexExpressCheckout",
            "baseName": "amex_express_checkout",
            "type": "object"
        },
        {
            "name": "applePay",
            "baseName": "apple_pay",
            "type": "object"
        },
        {
            "name": "dynamicLast4",
            "baseName": "dynamic_last4",
            "type": "string"
        },
        {
            "name": "googlePay",
            "baseName": "google_pay",
            "type": "object"
        },
        {
            "name": "masterpass",
            "baseName": "masterpass",
            "type": "PaymentMethodDetailsCardWalletMasterpass"
        },
        {
            "name": "samsungPay",
            "baseName": "samsung_pay",
            "type": "object"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentMethodDetailsCardWallet.TypeEnum"
        },
        {
            "name": "visaCheckout",
            "baseName": "visa_checkout",
            "type": "PaymentMethodDetailsCardWalletVisaCheckout"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsCardWallet.attributeTypeMap;
    }
}

export namespace PaymentMethodDetailsCardWallet {
    export enum TypeEnum {
        AmexExpressCheckout = <any> 'amex_express_checkout',
        ApplePay = <any> 'apple_pay',
        GooglePay = <any> 'google_pay',
        Masterpass = <any> 'masterpass',
        SamsungPay = <any> 'samsung_pay',
        VisaCheckout = <any> 'visa_checkout'
    }
}
