/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodDetailsCardInstallmentsPlan } from './paymentMethodDetailsCardInstallmentsPlan';

/**
* Installment plan selected for the payment.
*/
export class PaymentMethodDetailsCardInstallmentsPlan1 {
    /**
    * For `fixed_count` installment plans, this is the number of installment payments your customer will make to their credit card.
    */
    'count': number | null;
    /**
    * For `fixed_count` installment plans, this is the interval between installment payments your customer will make to their credit card. One of `month`.
    */
    'interval': PaymentMethodDetailsCardInstallmentsPlan1.IntervalEnum;
    /**
    * Type of installment plan, one of `fixed_count`.
    */
    'type': PaymentMethodDetailsCardInstallmentsPlan1.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "PaymentMethodDetailsCardInstallmentsPlan1.IntervalEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentMethodDetailsCardInstallmentsPlan1.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodDetailsCardInstallmentsPlan1.attributeTypeMap;
    }
}

export namespace PaymentMethodDetailsCardInstallmentsPlan1 {
    export enum IntervalEnum {
        Month = <any> 'month'
    }
    export enum TypeEnum {
        FixedCount = <any> 'fixed_count'
    }
}
