/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThreeDSecureUsage } from './threeDSecureUsage';

/**
* Contains details on how this Card may be used for 3D Secure authentication.
*/
export class PaymentMethodCardThreeDSecureUsage {
    /**
    * Whether 3D Secure is supported on this card.
    */
    'supported': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "supported",
            "baseName": "supported",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodCardThreeDSecureUsage.attributeTypeMap;
    }
}

