/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentPagesCheckoutSessionShippingOptionShippingRate } from './paymentPagesCheckoutSessionShippingOptionShippingRate';

/**
* 
*/
export class PaymentPagesCheckoutSessionShippingOption {
    /**
    * A non-negative integer in cents representing how much to charge.
    */
    'shippingAmount': number;
    'shippingRate': PaymentPagesCheckoutSessionShippingOptionShippingRate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shippingAmount",
            "baseName": "shipping_amount",
            "type": "number"
        },
        {
            "name": "shippingRate",
            "baseName": "shipping_rate",
            "type": "PaymentPagesCheckoutSessionShippingOptionShippingRate"
        }    ];

    static getAttributeTypeMap() {
        return PaymentPagesCheckoutSessionShippingOption.attributeTypeMap;
    }
}

