/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodSepaDebitGeneratedFrom } from './paymentMethodSepaDebitGeneratedFrom';

/**
* 
*/
export class PaymentMethodSepaDebit {
    /**
    * Bank code of bank associated with the bank account.
    */
    'bankCode': string | null;
    /**
    * Branch code of bank associated with the bank account.
    */
    'branchCode': string | null;
    /**
    * Two-letter ISO code representing the country the bank account is located in.
    */
    'country': string | null;
    /**
    * Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    */
    'fingerprint': string | null;
    'generatedFrom': PaymentMethodSepaDebitGeneratedFrom | null;
    /**
    * Last four characters of the IBAN.
    */
    'last4': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bankCode",
            "baseName": "bank_code",
            "type": "string"
        },
        {
            "name": "branchCode",
            "baseName": "branch_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "generatedFrom",
            "baseName": "generated_from",
            "type": "PaymentMethodSepaDebitGeneratedFrom"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodSepaDebit.attributeTypeMap;
    }
}

