/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentLinksResourceInvoiceCreationInvoiceData } from './paymentLinksResourceInvoiceCreationInvoiceData';

/**
* 
*/
export class PaymentLinksResourceInvoiceCreation {
    /**
    * Enable creating an invoice on successful payment.
    */
    'enabled': boolean;
    'invoiceData': PaymentLinksResourceInvoiceCreationInvoiceData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "invoiceData",
            "baseName": "invoice_data",
            "type": "PaymentLinksResourceInvoiceCreationInvoiceData"
        }    ];

    static getAttributeTypeMap() {
        return PaymentLinksResourceInvoiceCreation.attributeTypeMap;
    }
}

