/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown } from './paymentPagesCheckoutSessionTotalDetailsResourceBreakdown';

/**
* 
*/
export class PaymentPagesCheckoutSessionTotalDetails {
    /**
    * This is the sum of all the discounts.
    */
    'amountDiscount': number;
    /**
    * This is the sum of all the shipping amounts.
    */
    'amountShipping': number | null;
    /**
    * This is the sum of all the tax amounts.
    */
    'amountTax': number;
    'breakdown'?: PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountDiscount",
            "baseName": "amount_discount",
            "type": "number"
        },
        {
            "name": "amountShipping",
            "baseName": "amount_shipping",
            "type": "number"
        },
        {
            "name": "amountTax",
            "baseName": "amount_tax",
            "type": "number"
        },
        {
            "name": "breakdown",
            "baseName": "breakdown",
            "type": "PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown"
        }    ];

    static getAttributeTypeMap() {
        return PaymentPagesCheckoutSessionTotalDetails.attributeTypeMap;
    }
}

