/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PaymentMethodBoleto {
    /**
    * Uniquely identifies the customer tax id (CNPJ or CPF)
    */
    'taxId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taxId",
            "baseName": "tax_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodBoleto.attributeTypeMap;
    }
}

