/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PortalFlowsAfterCompletionRedirect {
    /**
    * The URL the customer will be redirected to after the flow is completed.
    */
    'returnUrl': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "returnUrl",
            "baseName": "return_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PortalFlowsAfterCompletionRedirect.attributeTypeMap;
    }
}

