/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PortalCustomerUpdate {
    /**
    * The types of customer updates that are supported. When empty, customers are not updateable.
    */
    'allowedUpdates': Array<PortalCustomerUpdate.AllowedUpdatesEnum>;
    /**
    * Whether the feature is enabled.
    */
    'enabled': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedUpdates",
            "baseName": "allowed_updates",
            "type": "Array<PortalCustomerUpdate.AllowedUpdatesEnum>"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PortalCustomerUpdate.attributeTypeMap;
    }
}

export namespace PortalCustomerUpdate {
    export enum AllowedUpdatesEnum {
        Address = <any> 'address',
        Email = <any> 'email',
        Name = <any> 'name',
        Phone = <any> 'phone',
        Shipping = <any> 'shipping',
        TaxId = <any> 'tax_id'
    }
}
