/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PortalFlowsFlowAfterCompletionHostedConfirmation } from './portalFlowsFlowAfterCompletionHostedConfirmation';
import { PortalFlowsFlowAfterCompletionRedirect } from './portalFlowsFlowAfterCompletionRedirect';

/**
* 
*/
export class PortalFlowsFlowAfterCompletion {
    'hostedConfirmation': PortalFlowsFlowAfterCompletionHostedConfirmation | null;
    'redirect': PortalFlowsFlowAfterCompletionRedirect | null;
    /**
    * The specified type of behavior after the flow is completed.
    */
    'type': PortalFlowsFlowAfterCompletion.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hostedConfirmation",
            "baseName": "hosted_confirmation",
            "type": "PortalFlowsFlowAfterCompletionHostedConfirmation"
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "PortalFlowsFlowAfterCompletionRedirect"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PortalFlowsFlowAfterCompletion.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PortalFlowsFlowAfterCompletion.attributeTypeMap;
    }
}

export namespace PortalFlowsFlowAfterCompletion {
    export enum TypeEnum {
        HostedConfirmation = <any> 'hosted_confirmation',
        PortalHomepage = <any> 'portal_homepage',
        Redirect = <any> 'redirect'
    }
}
