/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PriceTier {
    /**
    * Price for the entire tier.
    */
    'flatAmount': number | null;
    /**
    * Same as `flat_amount`, but contains a decimal value with at most 12 decimal places.
    */
    'flatAmountDecimal': string | null;
    /**
    * Per unit price for units relevant to the tier.
    */
    'unitAmount': number | null;
    /**
    * Same as `unit_amount`, but contains a decimal value with at most 12 decimal places.
    */
    'unitAmountDecimal': string | null;
    /**
    * Up to and including to this quantity will be contained in the tier.
    */
    'upTo': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flatAmount",
            "baseName": "flat_amount",
            "type": "number"
        },
        {
            "name": "flatAmountDecimal",
            "baseName": "flat_amount_decimal",
            "type": "string"
        },
        {
            "name": "unitAmount",
            "baseName": "unit_amount",
            "type": "number"
        },
        {
            "name": "unitAmountDecimal",
            "baseName": "unit_amount_decimal",
            "type": "string"
        },
        {
            "name": "upTo",
            "baseName": "up_to",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PriceTier.attributeTypeMap;
    }
}

