/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { QuotesResourceTotalDetails } from './quotesResourceTotalDetails';

/**
* 
*/
export class QuotesResourceRecurring {
    /**
    * Total before any discounts or taxes are applied.
    */
    'amountSubtotal': number;
    /**
    * Total after discounts and taxes are applied.
    */
    'amountTotal': number;
    /**
    * The frequency at which a subscription is billed. One of `day`, `week`, `month` or `year`.
    */
    'interval': QuotesResourceRecurring.IntervalEnum;
    /**
    * The number of intervals (specified in the `interval` attribute) between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months.
    */
    'intervalCount': number;
    'totalDetails': QuotesResourceTotalDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountSubtotal",
            "baseName": "amount_subtotal",
            "type": "number"
        },
        {
            "name": "amountTotal",
            "baseName": "amount_total",
            "type": "number"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "QuotesResourceRecurring.IntervalEnum"
        },
        {
            "name": "intervalCount",
            "baseName": "interval_count",
            "type": "number"
        },
        {
            "name": "totalDetails",
            "baseName": "total_details",
            "type": "QuotesResourceTotalDetails"
        }    ];

    static getAttributeTypeMap() {
        return QuotesResourceRecurring.attributeTypeMap;
    }
}

export namespace QuotesResourceRecurring {
    export enum IntervalEnum {
        Day = <any> 'day',
        Month = <any> 'month',
        Week = <any> 'week',
        Year = <any> 'year'
    }
}
