/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RadarEarlyFraudWarningCharge } from './radarEarlyFraudWarningCharge';
import { RadarEarlyFraudWarningPaymentIntent } from './radarEarlyFraudWarningPaymentIntent';

/**
* An early fraud warning indicates that the card issuer has notified us that a charge may be fraudulent.  Related guide: [Early Fraud Warnings](https://stripe.com/docs/disputes/measuring#early-fraud-warnings).
*/
export class RadarEarlyFraudWarning {
    /**
    * An EFW is actionable if it has not received a dispute and has not been fully refunded. You may wish to proactively refund a charge that receives an EFW, in order to avoid receiving a dispute later.
    */
    'actionable': boolean;
    'charge': RadarEarlyFraudWarningCharge;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created': number;
    /**
    * The type of fraud labelled by the issuer. One of `card_never_received`, `fraudulent_card_application`, `made_with_counterfeit_card`, `made_with_lost_card`, `made_with_stolen_card`, `misc`, `unauthorized_use_of_card`.
    */
    'fraudType': string;
    /**
    * Unique identifier for the object.
    */
    'id': string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode': boolean;
    /**
    * String representing the object\'s type. Objects of the same type share the same value.
    */
    'object': RadarEarlyFraudWarning.ObjectEnum;
    'paymentIntent'?: RadarEarlyFraudWarningPaymentIntent;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actionable",
            "baseName": "actionable",
            "type": "boolean"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "RadarEarlyFraudWarningCharge"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "fraudType",
            "baseName": "fraud_type",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "RadarEarlyFraudWarning.ObjectEnum"
        },
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "RadarEarlyFraudWarningPaymentIntent"
        }    ];

    static getAttributeTypeMap() {
        return RadarEarlyFraudWarning.attributeTypeMap;
    }
}

export namespace RadarEarlyFraudWarning {
    export enum ObjectEnum {
        RadarEarlyFraudWarning = <any> 'radar.early_fraud_warning'
    }
}
