/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class ReceivedPaymentMethodDetailsFinancialAccount {
    /**
    * The FinancialAccount ID.
    */
    'id': string;
    /**
    * The rails the ReceivedCredit was sent over. A FinancialAccount can only send funds over `stripe`.
    */
    'network': ReceivedPaymentMethodDetailsFinancialAccount.NetworkEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "ReceivedPaymentMethodDetailsFinancialAccount.NetworkEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReceivedPaymentMethodDetailsFinancialAccount.attributeTypeMap;
    }
}

export namespace ReceivedPaymentMethodDetailsFinancialAccount {
    export enum NetworkEnum {
        Stripe = <any> 'stripe'
    }
}
