/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RefundNextActionDisplayDetails1 } from './refundNextActionDisplayDetails1';

/**
* 
*/
export class RefundNextAction {
    'displayDetails': RefundNextActionDisplayDetails1 | null;
    /**
    * Type of the next action to perform.
    */
    'type': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayDetails",
            "baseName": "display_details",
            "type": "RefundNextActionDisplayDetails1"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RefundNextAction.attributeTypeMap;
    }
}

