/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LinkedAccountOptionsUsBankAccount } from './linkedAccountOptionsUsBankAccount';

/**
* 
*/
export class SetupIntentPaymentMethodOptionsUsBankAccount {
    'financialConnections'?: LinkedAccountOptionsUsBankAccount;
    /**
    * Bank account verification method.
    */
    'verificationMethod'?: SetupIntentPaymentMethodOptionsUsBankAccount.VerificationMethodEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "financialConnections",
            "baseName": "financial_connections",
            "type": "LinkedAccountOptionsUsBankAccount"
        },
        {
            "name": "verificationMethod",
            "baseName": "verification_method",
            "type": "SetupIntentPaymentMethodOptionsUsBankAccount.VerificationMethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return SetupIntentPaymentMethodOptionsUsBankAccount.attributeTypeMap;
    }
}

export namespace SetupIntentPaymentMethodOptionsUsBankAccount {
    export enum VerificationMethodEnum {
        Automatic = <any> 'automatic',
        Instant = <any> 'instant',
        Microdeposits = <any> 'microdeposits'
    }
}
