/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ShippingRateCurrencyOption } from './shippingRateCurrencyOption';

/**
* 
*/
export class ShippingRateFixedAmount {
    /**
    * A non-negative integer in cents representing how much to charge.
    */
    'amount': number;
    /**
    * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    */
    'currency': string;
    /**
    * Shipping rates defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
    */
    'currencyOptions'?: { [key: string]: ShippingRateCurrencyOption; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "currencyOptions",
            "baseName": "currency_options",
            "type": "{ [key: string]: ShippingRateCurrencyOption; }"
        }    ];

    static getAttributeTypeMap() {
        return ShippingRateFixedAmount.attributeTypeMap;
    }
}

