/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SourceOwnerAddress } from './sourceOwnerAddress';
import { SourceOwnerVerifiedAddress } from './sourceOwnerVerifiedAddress';

/**
* 
*/
export class SourceOwner {
    'address': SourceOwnerAddress | null;
    /**
    * Owner\'s email address.
    */
    'email': string | null;
    /**
    * Owner\'s full name.
    */
    'name': string | null;
    /**
    * Owner\'s phone number (including extension).
    */
    'phone': string | null;
    'verifiedAddress': SourceOwnerVerifiedAddress | null;
    /**
    * Verified owner\'s email address. Verified values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'verifiedEmail': string | null;
    /**
    * Verified owner\'s full name. Verified values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'verifiedName': string | null;
    /**
    * Verified owner\'s phone number (including extension). Verified values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement. They cannot be set or mutated.
    */
    'verifiedPhone': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "SourceOwnerAddress"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "verifiedAddress",
            "baseName": "verified_address",
            "type": "SourceOwnerVerifiedAddress"
        },
        {
            "name": "verifiedEmail",
            "baseName": "verified_email",
            "type": "string"
        },
        {
            "name": "verifiedName",
            "baseName": "verified_name",
            "type": "string"
        },
        {
            "name": "verifiedPhone",
            "baseName": "verified_phone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SourceOwner.attributeTypeMap;
    }
}

