/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SourceTypeCard {
    'addressLine1Check'?: string | null;
    'addressZipCheck'?: string | null;
    'brand'?: string | null;
    'country'?: string | null;
    'cvcCheck'?: string | null;
    'description'?: string;
    'dynamicLast4'?: string | null;
    'expMonth'?: number | null;
    'expYear'?: number | null;
    'fingerprint'?: string;
    'funding'?: string | null;
    'iin'?: string;
    'issuer'?: string;
    'last4'?: string | null;
    'name'?: string | null;
    'threeDSecure'?: string;
    'tokenizationMethod'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addressLine1Check",
            "baseName": "address_line1_check",
            "type": "string"
        },
        {
            "name": "addressZipCheck",
            "baseName": "address_zip_check",
            "type": "string"
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "cvcCheck",
            "baseName": "cvc_check",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "dynamicLast4",
            "baseName": "dynamic_last4",
            "type": "string"
        },
        {
            "name": "expMonth",
            "baseName": "exp_month",
            "type": "number"
        },
        {
            "name": "expYear",
            "baseName": "exp_year",
            "type": "number"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string"
        },
        {
            "name": "funding",
            "baseName": "funding",
            "type": "string"
        },
        {
            "name": "iin",
            "baseName": "iin",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "threeDSecure",
            "baseName": "three_d_secure",
            "type": "string"
        },
        {
            "name": "tokenizationMethod",
            "baseName": "tokenization_method",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SourceTypeCard.attributeTypeMap;
    }
}

