/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvoiceSettingSubscriptionScheduleSetting } from './invoiceSettingSubscriptionScheduleSetting';

/**
* The invoice settings applicable during this phase.
*/
export class SubscriptionSchedulePhaseConfigurationInvoiceSettings {
    /**
    * Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
    */
    'daysUntilDue': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "daysUntilDue",
            "baseName": "days_until_due",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionSchedulePhaseConfigurationInvoiceSettings.attributeTypeMap;
    }
}

