/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Defines how a subscription behaves when a free trial ends.
*/
export class SubscriptionsTrialsResourceEndBehavior {
    /**
    * Indicates how the subscription should change when the trial ends if the user did not provide a payment method.
    */
    'missingPaymentMethod': SubscriptionsTrialsResourceEndBehavior.MissingPaymentMethodEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "missingPaymentMethod",
            "baseName": "missing_payment_method",
            "type": "SubscriptionsTrialsResourceEndBehavior.MissingPaymentMethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionsTrialsResourceEndBehavior.attributeTypeMap;
    }
}

export namespace SubscriptionsTrialsResourceEndBehavior {
    export enum MissingPaymentMethodEnum {
        Cancel = <any> 'cancel',
        CreateInvoice = <any> 'create_invoice',
        Pause = <any> 'pause'
    }
}
