/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class SubscriptionPendingInvoiceItemInterval {
    /**
    * Specifies invoicing frequency. Either `day`, `week`, `month` or `year`.
    */
    'interval': SubscriptionPendingInvoiceItemInterval.IntervalEnum;
    /**
    * The number of intervals between invoices. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of one year interval allowed (1 year, 12 months, or 52 weeks).
    */
    'intervalCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "interval",
            "baseName": "interval",
            "type": "SubscriptionPendingInvoiceItemInterval.IntervalEnum"
        },
        {
            "name": "intervalCount",
            "baseName": "interval_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPendingInvoiceItemInterval.attributeTypeMap;
    }
}

export namespace SubscriptionPendingInvoiceItemInterval {
    export enum IntervalEnum {
        Day = <any> 'day',
        Month = <any> 'month',
        Week = <any> 'week',
        Year = <any> 'year'
    }
}
