/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TerminalReaderReaderResourceProcessConfig } from './terminalReaderReaderResourceProcessConfig';
import { TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent } from './terminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent';

/**
* Represents a reader action to process a payment intent
*/
export class TerminalReaderReaderResourceProcessPaymentIntentAction {
    'paymentIntent': TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent;
    'processConfig'?: TerminalReaderReaderResourceProcessConfig;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentIntent",
            "baseName": "payment_intent",
            "type": "TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent"
        },
        {
            "name": "processConfig",
            "baseName": "process_config",
            "type": "TerminalReaderReaderResourceProcessConfig"
        }    ];

    static getAttributeTypeMap() {
        return TerminalReaderReaderResourceProcessPaymentIntentAction.attributeTypeMap;
    }
}

