/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssuingAuthorization } from './issuingAuthorization';
import { TreasuryCreditReversal } from './treasuryCreditReversal';
import { TreasuryDebitReversal } from './treasuryDebitReversal';
import { TreasuryInboundTransfer } from './treasuryInboundTransfer';
import { TreasuryOutboundPayment } from './treasuryOutboundPayment';
import { TreasuryOutboundTransfer } from './treasuryOutboundTransfer';
import { TreasuryReceivedCredit } from './treasuryReceivedCredit';
import { TreasuryReceivedDebit } from './treasuryReceivedDebit';
import { TreasuryTransactionsResourceFlowDetails } from './treasuryTransactionsResourceFlowDetails';

/**
* Details of the flow associated with the TransactionEntry.
*/
export class TreasuryTransactionEntryFlowDetails {
    'creditReversal'?: TreasuryCreditReversal;
    'debitReversal'?: TreasuryDebitReversal;
    'inboundTransfer'?: TreasuryInboundTransfer;
    'issuingAuthorization'?: IssuingAuthorization;
    'outboundPayment'?: TreasuryOutboundPayment;
    'outboundTransfer'?: TreasuryOutboundTransfer;
    'receivedCredit'?: TreasuryReceivedCredit;
    'receivedDebit'?: TreasuryReceivedDebit;
    /**
    * Type of the flow that created the Transaction. Set to the same value as `flow_type`.
    */
    'type': TreasuryTransactionEntryFlowDetails.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creditReversal",
            "baseName": "credit_reversal",
            "type": "TreasuryCreditReversal"
        },
        {
            "name": "debitReversal",
            "baseName": "debit_reversal",
            "type": "TreasuryDebitReversal"
        },
        {
            "name": "inboundTransfer",
            "baseName": "inbound_transfer",
            "type": "TreasuryInboundTransfer"
        },
        {
            "name": "issuingAuthorization",
            "baseName": "issuing_authorization",
            "type": "IssuingAuthorization"
        },
        {
            "name": "outboundPayment",
            "baseName": "outbound_payment",
            "type": "TreasuryOutboundPayment"
        },
        {
            "name": "outboundTransfer",
            "baseName": "outbound_transfer",
            "type": "TreasuryOutboundTransfer"
        },
        {
            "name": "receivedCredit",
            "baseName": "received_credit",
            "type": "TreasuryReceivedCredit"
        },
        {
            "name": "receivedDebit",
            "baseName": "received_debit",
            "type": "TreasuryReceivedDebit"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TreasuryTransactionEntryFlowDetails.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return TreasuryTransactionEntryFlowDetails.attributeTypeMap;
    }
}

export namespace TreasuryTransactionEntryFlowDetails {
    export enum TypeEnum {
        CreditReversal = <any> 'credit_reversal',
        DebitReversal = <any> 'debit_reversal',
        InboundTransfer = <any> 'inbound_transfer',
        IssuingAuthorization = <any> 'issuing_authorization',
        Other = <any> 'other',
        OutboundPayment = <any> 'outbound_payment',
        OutboundTransfer = <any> 'outbound_transfer',
        ReceivedCredit = <any> 'received_credit',
        ReceivedDebit = <any> 'received_debit'
    }
}
