/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* ABA Records contain U.S. bank account details per the ABA format.
*/
export class TreasuryFinancialAccountsResourceAbaRecord {
    /**
    * The name of the person or business that owns the bank account.
    */
    'accountHolderName': string;
    /**
    * The account number.
    */
    'accountNumber': string | null;
    /**
    * The last four characters of the account number.
    */
    'accountNumberLast4': string;
    /**
    * Name of the bank.
    */
    'bankName': string;
    /**
    * Routing number for the account.
    */
    'routingNumber': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolderName",
            "baseName": "account_holder_name",
            "type": "string"
        },
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "accountNumberLast4",
            "baseName": "account_number_last4",
            "type": "string"
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TreasuryFinancialAccountsResourceAbaRecord.attributeTypeMap;
    }
}

