/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails } from './treasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails';

/**
* Details about the end user.
*/
export class TreasuryOutboundPaymentEndUserDetails {
    /**
    * IP address of the user initiating the OutboundPayment. Set if `present` is set to `true`. IP address collection is required for risk and compliance reasons. This will be used to help determine if the OutboundPayment is authorized or should be blocked.
    */
    'ipAddress': string | null;
    /**
    * `true`` if the OutboundPayment creation request is being made on behalf of an end user by a platform. Otherwise, `false`.
    */
    'present': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ipAddress",
            "baseName": "ip_address",
            "type": "string"
        },
        {
            "name": "present",
            "baseName": "present",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TreasuryOutboundPaymentEndUserDetails.attributeTypeMap;
    }
}

