/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TreasuryFinancialAccountsResourcePlatformRestrictions } from './treasuryFinancialAccountsResourcePlatformRestrictions';

/**
* The set of functionalities that the platform can restrict on the FinancialAccount.
*/
export class TreasuryFinancialAccountPlatformRestrictions {
    /**
    * Restricts all inbound money movement.
    */
    'inboundFlows': TreasuryFinancialAccountPlatformRestrictions.InboundFlowsEnum;
    /**
    * Restricts all outbound money movement.
    */
    'outboundFlows': TreasuryFinancialAccountPlatformRestrictions.OutboundFlowsEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inboundFlows",
            "baseName": "inbound_flows",
            "type": "TreasuryFinancialAccountPlatformRestrictions.InboundFlowsEnum"
        },
        {
            "name": "outboundFlows",
            "baseName": "outbound_flows",
            "type": "TreasuryFinancialAccountPlatformRestrictions.OutboundFlowsEnum"
        }    ];

    static getAttributeTypeMap() {
        return TreasuryFinancialAccountPlatformRestrictions.attributeTypeMap;
    }
}

export namespace TreasuryFinancialAccountPlatformRestrictions {
    export enum InboundFlowsEnum {
        Restricted = <any> 'restricted',
        Unrestricted = <any> 'unrestricted'
    }
    export enum OutboundFlowsEnum {
        Restricted = <any> 'restricted',
        Unrestricted = <any> 'unrestricted'
    }
}
