/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TreasuryFinancialAccountsResourceAchToggleSettings } from './treasuryFinancialAccountsResourceAchToggleSettings';
import { TreasuryFinancialAccountsResourceToggleSettings } from './treasuryFinancialAccountsResourceToggleSettings';

/**
* OutboundTransfers contains outbound transfers features for a FinancialAccount.
*/
export class TreasuryFinancialAccountsResourceOutboundTransfers {
    'ach'?: TreasuryFinancialAccountsResourceAchToggleSettings;
    'usDomesticWire'?: TreasuryFinancialAccountsResourceToggleSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ach",
            "baseName": "ach",
            "type": "TreasuryFinancialAccountsResourceAchToggleSettings"
        },
        {
            "name": "usDomesticWire",
            "baseName": "us_domestic_wire",
            "type": "TreasuryFinancialAccountsResourceToggleSettings"
        }    ];

    static getAttributeTypeMap() {
        return TreasuryFinancialAccountsResourceOutboundTransfers.attributeTypeMap;
    }
}

