/**
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2022-11-15
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class UsBankAccountNetworks {
    /**
    * The preferred network.
    */
    'preferred': string | null;
    /**
    * All supported networks.
    */
    'supported': Array<UsBankAccountNetworks.SupportedEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preferred",
            "baseName": "preferred",
            "type": "string"
        },
        {
            "name": "supported",
            "baseName": "supported",
            "type": "Array<UsBankAccountNetworks.SupportedEnum>"
        }    ];

    static getAttributeTypeMap() {
        return UsBankAccountNetworks.attributeTypeMap;
    }
}

export namespace UsBankAccountNetworks {
    export enum SupportedEnum {
        Ach = <any> 'ach',
        UsDomesticWire = <any> 'us_domestic_wire'
    }
}
